wg_peers:
- name: dn42lon-strexp
  remove: true

- name: dn42fra-owens
  port: 51099
  remote: "95.179.250.248:1269"
  wg_pubkey: "13NKYtCKbBw2ZzhFLSO5HaQJdVBnv8pi2cbIgDauhwE="
  peer_v4: "172.21.99.137/32"
  peer_v6: "fd42:4242:1099:179::69/128"
  local_v4: 172.20.229.116
  local_v6: fd86:bad:11b7:116::1
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42par-raito
  port: 51457
  remote: "[2a01:e0a:5f9:9681::2]:21080"
  wg_pubkey: "5TxBJx9R22Du8cuoE4y59SdERwmgfmDF+9lmnIE8XD8="
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63623763346461306535343534323664306361343234363937346362356337393230316131326164
    6162346231316265653531316132613831326332653139610a393835383966343636363935393539
    63373765373166383936373331623233363538383931373463303761663130633033316363303361
    6262363136353437380a656165643835313730363136383466356331323665353661316537646335
    63656666383139653565376539616663643766613630343634386235663733393661316566356332
    3838613836383936323462386563643563373539353837626464
  peer_v4: null
  peer_v6: "fd4d:ce73:68f9:9a62::3"
  local_v4: 172.20.229.116
  local_v6: fd86:bad:11b7:116::1
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42ams-jerry
  port: 53618
  remote: "nl.neo.jerryxiao.cc:50090"
  wg_pubkey: "zE9C015v2H0duvNBdXm2ToWqimoIlBqtZtFTqgLQXgs="
  peer_v4: null
  peer_v6: "fe80::3618/64"
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42hel-andi
  port: 53991
  remote: "iota.h4ck.space:42029"
  wg_pubkey: "s6OL5S5GvUykOs1XVAWL2i6Mflk6niZ4BZhrHmdB5Gw="
  peer_v4: null
  peer_v6: "fe80::1"
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42rbx-serverm
  port: 53770
  remote: "rbx1.dn42.servermade.com:51080"
  wg_pubkey: "0ndXPAg17zmVx5CfxMblRfdcDjHRDB6OKBkYvvtq1g0="
  peer_v4: "172.22.118.129"
  peer_v6: "fe80::3770/64"
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42lon-wcysite
  remove: true

- name: dn42-usman
  port: 21869
  remote: fr-lil1.dn42.usman.network:21080
  wg_pubkey: qwjXj/6R9ThUnqeOAYN+MxM6CbIgzjS8WFDdXuyEpHY=
  peer_v4: null
  peer_v6: fe80::1869

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: uk1.dn42.atolm.net:21080
  wg_pubkey: W5tOp5Iw/uJppISGF9KSQL5/q9ykW0PUSAKDe4YPXHQ=
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-rhysperry
  peer_v4: 172.22.76.1
  peer_v6: null
  port: 23665
  remote: rhysperry.com:55505
  wg_pubkey: I1WlxMXrSoN2g3WVJNYNG+4MsYhJwNA6UYgt5pHOGGY=
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-htw
  peer_v4: 172.21.78.33
  peer_v6: fe80::1440:1080
  port: 21440
  remote: sco1.dn42.canidae.systems:26005
  wg_pubkey: YoB/Tge5Teb1ycnbi/vjmcsyD8My4waVkNhupn7JnDk=
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-bandura
  peer_v4: 172.22.149.225
  peer_v6: fe80::2923
  port: 22923
  remote: p2p-node.de:51080
  wg_pubkey: 4gf9k6UUBO55geG7377qiMt/zHVuy77X60n/vNQMtj4=
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-librehouse
  peer_v4: 10.127.8.3
  peer_v6: fd46:e3dc:db4a:1::3
  port: 21037
  remote: setsuna.yukipedia.cf:51080
  wg_pubkey: jQqFNQ/nxRSeJ/KPcRDGxswxAs59MuCc0aWX3OZ+7HA=
  local_v4: 172.20.229.116
  local_v6: fd86:bad:11b7:116::1
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-scooter
  port: 23856
  remote: lon-uk.dn42.ca:21080
  wg_pubkey: 7xvugzmlWteydIZnvNls/ZwoA2Acvd7Uq5FO66KSPFg=
  peer_v4: 172.23.109.171
  peer_v6: fd38:cfa3:7091:2::1
  local_v4: 172.20.229.116
  local_v6: fd86:bad:11b7:116::1
  wg_privkey: /etc/wireguard/privatekey_lon

- name: dn42-nyabla
  port: 20850
  remote: meow.nyabla.net:21080
  wg_pubkey: sRUVGY3OjySTLefDVYnSBItdjNZSAUdvG+P8vBNWdBg=
  peer_v4: null
  peer_v6: fe80::0850
  local_v4: 172.20.229.116
  local_v6: fe80::116
  wg_privkey: /etc/wireguard/privatekey_lon
# end migrated from lon

- name: dn42ams-jrb0001
  port: 50119
  remote: "95.179.134.138:21080"
  wg_pubkey: "hwEFCjMf4xzaXzsmk4JdPllJjuxC3r7UPjL632A+L3M="
  peer_v4: "172.20.1.1"
  peer_v6: "fe80::119"

- name: dn42ams-aureus
  port: 50007
  remote: "s.hanfucw.com:8558"
  wg_pubkey: "ViMRAXJbz8rxqiXUljsx3gF0nLG9a612Qr6DllYLs3k="
  peer_v4: "10.127.8.185"
  peer_v6: "fd10:127:7::1"

- name: "dn42ams-tomkap"
  port: 52092
  remote: "nl0.dn42.pebkac.gr:51080"
  wg_pubkey: "g4MJv6qMPwbffxNjUKmIa5Yhf5ZzRqjIMzMHCSiFQgs="
  peer_v4: 172.21.67.200/32
  peer_v6: "fe80::42:1080:1/128"

- name: dn42fra-welterd
  port: 54738
  remote: "gate1.defra0.dn42.welterde.net:42002"
  wg_pubkey: "I68Jv8818pk2NX0GC8ul18095/iZ66XCxJuo/brk/Go="
  peer_v4: null
  peer_v6: "fe80::fcde:3558"

- name: dn42ams-yura
  remove: true

- name: dn42osl-yurui
  port: 52330
  remote: "osl01.kn.node.argonauts.xyz:51080"
  wg_pubkey: "POZ2ZRRPbQtfcb1d0eiNeKlBVqJiYFQ4/naY/xfkfDQ="
  peer_v4: "172.23.32.3"
  peer_v6: "fe80::2330:1"

- name: dn42ams-mayli
  port: 51123
  remote: "ams.ccp.ovh:21080"
  wg_pubkey: "e5X1ZlZUOVtTFeWi+d6cUqqNaXB0F2UHwbquAKU4z3I="
  peer_v4: "172.20.47.2"
  peer_v6: "fe80::1123"

- name: dn42ams-camelus
  port: 21592
  remote: "nl01.dn42.trampel.org:41080"
  wg_pubkey: "RcXm6OK+3+/sjXoivNTdjU3W5ctdohZ9GKYS25f05n8="
  peer_v4: "172.21.99.189"
  peer_v6: "fe80::1592"

- name: dn42dus-tsingya
  port: 23699
  remote: "dus-de.tsingyao.pub:21080"
  wg_pubkey: "xyhzHBpNDQlyeNG44xaU5zz86+Qeig8v6/PTutZqCRM="
  peer_v4: "172.22.155.9"
  peer_v6: "fe80::42:3699:9"

- name: dn42prg-wg
  port: 22331
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64646433373431313533623962626635303161653437306335303337393430353431373566626130
    3835316463646631613266363139336638363130396134390a653137663236343639623334663437
    36333962386339343033663962363461396535323963303035363364393330663931626636613931
    6437346437303264620a633363653965656331386163333263316639613436376633336466383962
    62653433383734323130396566333735346465346338633839343134303336616134
  wg_pubkey: "22Yg+PozQDDJUufe2POaV/ron0wZ6LVznpMgrRZDAXI="
  peer_v4: null
  peer_v6: "fe80::2331"

- name: dn42mow-dgy
  port: 20826
  remote: "ru.dn42.dgy.xyz:21080"
  wg_pubkey: "Y8E2cd2DKr7hZ3qs1WgU+2l+qWHaOxw4vFPAGevpiW0="
  peer_v4: null
  peer_v6: "fe80::826"

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030:c
  port: 22717
  remote: nl.vm.whojk.com:23010
  wg_pubkey: cokP4jFBH0TlBD/m3sWCpc9nADLOhzM2+lcjAb3ynFc=

- name: dn42-iedon
  peer_v4: 172.23.91.125
  peer_v6: fe80::2189:e9
  port: 22189
  remote: de-fra.dn42.kuu.moe:58384
  wg_pubkey: FHp0OR4UpAS8/Ra0FUNffTk18soUYCa6NcvZdOgxY0k=

- name: dn42-bling
  peer_v4: 172.20.21.106
  peer_v6: fe80::2333
  port: 20212
  remote: ams1.dn42.blw.moe:21080
  wg_pubkey: HXF4JPhmBCYL/e/mjdvxyiII8WchPQLK8AUVwTNPe3Q=

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: eu-west1.nodes.huajinet.org:21080
  wg_pubkey: dDM/rtklvpKHeIOKeLGjfYBTl+jEuhlr7dMIOdXbliU=

- name: dn42-spf
  peer_v4: 172.23.24.35
  peer_v6: fe80::ade0
  port: 21964
  remote: nl2.dn42.southparkfan.org:41080
  wg_pubkey: GsmcrWbFTcje5e+hmc0D6qonrkTpHksGZuk0cLBjDmY=

- name: dn42waw-filip
  port: 21404
  remote: "176.122.215.101:65001"
  wg_pubkey: "oZXF/BkUUpHDxgze+pYqSvoLv2JGkkemKSGWU9t3cWk="
  peer_v4: "172.20.178.65"
  peer_v6: "fe80::feec:daff:fe46:d60e/64"

- name: dn42-dingemans
  peer_v4: 172.23.89.146
  peer_v6: fe80::3:349a
  port: 20074
  remote: dn42.dingemans.tk:51820
  wg_pubkey: 8qZ8e5XG6G1OE3F/yGTB7iCIvV9IouHzpf+cSyPadxY=

- name: dn42-ty3r0x
  port: 22596
  remote: incognet.chaox.ro:21080
  wg_pubkey: sxIWYIrbJKKnUjnQ/SIbcUlhYsBGZcAujnT9Xn5mdFw=
  peer_v4: 169.254.42.5
  peer_v6: fe80::2596:5

- name: dn42-techanit
  peer_v4: null
  peer_v6: fe80::2206
  port: 22206
  remote: de1.dn42.est-it.de:13237
  wg_pubkey: QqcsQ6gRaK0ZxRskCxWoNeV2vd53/9IW/XfwjMMSjk8=

- name: dn42-arisum
  remove: true

- name: dn42-oscrx
  peer_v4: null
  peer_v6: fd69:420:cafe::1
  port: 23818
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63333136613963363534326231666332316138653639663733333565393064613735323630383137
    3664626230386532613166613633383162653564333032350a646563303338306564643637396333
    38326334316236343638333866343135366163373039306636323136633534333936666361646638
    3831356636613937610a623630613633653032333561336636623937303535393834663332353962
    37326236393661643637356430373931396530656665386534373137326166383464
  wg_pubkey: UDn35z45Uh9DxDL6zrHmFChjV0sYWlyPrwjUFe8ofTU=

- name: dn42-tmnet
  peer_v4: null
  peer_v6: fe80::cafe
  port: 23089
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    66626638373330613830346563396630646132386233366130336135373931613033643533626462
    3230313238303763636133336532303234373636393335320a333639333365363462386231663634
    34623562326166376262646431393934626433336161646234383361323131636236613764666131
    3530393166633661350a393130653439656665323463313565613830303734383461393639373762
    66613637636331366163363037363534393135626638376432623561333935393839
  wg_pubkey: CpZ6YCfbGVIW56OZGUlqAtMRyiR4b+vMZaoyF+rbX0Y=

- name: dn42-pigeonhole
  peer_v4: 172.22.145.25
  peer_v6: fe80::2458
  port: 22458
  remote: ipv4.nl-ams-a.nodes.pigeonhole.eu.org:21080
  wg_pubkey: QJnmWUnPS9wKKkLHHuWBYMGAI20MH9OEo28O4qr5DV8=

- name: dn42-lare
  port: 23035
  remote: uk01.dn42.lare.cc:21080
  wg_pubkey: RJaU1kRfiOREvKihiDMFpNrEGpN8td3z+UvHxabOlR0=
  peer_v4: null
  peer_v6: fe80::3035:138

- name: dn42-yukino
  port: 21255
  remote: dn42-nl-ams2.acgcl.net:31080
  wg_pubkey: jFePS+PHWK96lvbhPo5QrC6VoPwv5qSOmsT4OVOopi0=
  peer_v4: null
  peer_v6: fe80::1080

- name: dn42-eki
  remove: true

- name: dn42-marlinc
  remove: true

- name: dn42-ventilaar
  port: 22246
  remote: ams01.dn42.ventilaar.net:31080
  wg_pubkey: Z6WFjvsKIh4E92jxOYC07Dn5Q5Cc/pBFFpYlYZUr7j8=
  peer_v4: null
  peer_v6: fe80::224

- name: dn42-szczot3k
  port: 29680
  remote: ams1.as199680.net:30001
  wg_pubkey: /2PiRi0hn4ZpCX2Kfu9+/pLw6tOwC09nO1VBP/FywkM=
  peer_v4: null
  peer_v6: fe80::9680:64

- name: dn42-stetsed
  port: 23709
  remote: dn42-nl.selfhostable.net:51080
  wg_pubkey: cfV8qAhHcqootASac7fj86Lr6zf+3tW4Xa8tJeBxuUE=
  peer_v4: null
  peer_v6: fe80::3709
