wg_peers:
- name: dn42-tech9
  peer_v4: 172.20.16.143
  peer_v6: fe80::1588
  port: 21588
  remote: us-qas01.dn42.tech9.io:57225
  wg_pubkey: itmJ4Z8V1aNN368P6kMzuQM+GdzWbBKZjJiXrgSeGlw=
  local_v6: fe80::100
  bgp:
    asn: 4242421588
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.iad1.routedbits.com:51080
  wg_pubkey: /RLM4EcF8b7FKKcxnvHIYyDoES59HXIBqhKEWt4yRy0=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-burble
  port: 22601
  remote: dn42-us-ash1.burble.com:21080
  wg_pubkey: NyNVeb5VPSZ/HlEbX1NEzZ6qjKURX7vxmkR59ev3wCs=
  peer_v4: null
  peer_v6: fe80::42:2601:37:1
  bgp:
    asn: 4242422601
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-darkpoint
  port: 20150
  remote: iad.darkpoint.xyz:20150
  wg_pubkey: 1o0XfQvBM1gqknqzfuOnVmf2RjRTHuyMZYNipSSb2TQ=
  peer_v4: null
  peer_v6: fe80::150
  bgp:
    asn: 4242420150
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-prefixlabs
  port: 21240
  remote: us-01.prefixlabs.net:21080
  wg_pubkey: uRYzFGi+/B6pD0FR2SW3G/OzC5LPJXePNIt0s+nJfW0=
  peer_v4: 172.20.209.11
  peer_v6: fe80::1240:2
  bgp:
    asn: 4242421240
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-kioubit
  port: 23914
  remote: us2.g-load.eu:21080
  wg_pubkey: 6Cylr9h1xFduAO+5nyXhFI1XJ0+Sw9jCpCDvcqErF1s=
  peer_v4: 172.20.53.98
  peer_v6: fe80::ade0
  bgp:
    asn: 4242423914
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cow
  port: 23222
  remote: cow.computer:51852
  wg_pubkey: FMqnPe0y67hTl5ppPp/g3KrGtcM7KGUCf2ZHa3omOio=
  peer_v4: null
  peer_v6: fe80::3222:2
  bgp:
    asn: 4242423222
    ipv4: false
    ipv6: true
    mp_bgp: false
    extended_next_hop: false

- name: dn42-bandura
  port: 22923
  remote: trolljaeger.mk16.de:51080
  wg_pubkey: jDu5AIEJ437ngZLXkEi4RBcXPHpCdyOtY5eBSDd3kC0=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30396639646335346165653934646638323534323261636631353062376630376265636631356662
    3637306465356230626432383939646337343862383531300a346335376537343261393933353464
    33323830386238613434373634363530363235386662346135643930353832653066313232313034
    3862323939306665630a316439643137363464663336643265663165343764393762663233353362
    34353831383332333662373238666539386532373538313839666338356337633136336532313930
    3932313864316338663339363763363737356664653136356436
  bgp:
    asn: 4242422923
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
