wg_peers:
- name: dn42-napsterbat
  port: 51050
  remote: atl1-us.dn42.napshome.net:51080
  wg_pubkey: "Cro0O53QVO63240SyAu1vkF7kOa/KeMIwT8+7qGV9lI="
  peer_v4: "172.22.169.128"
  peer_v6: "fda9:26a9:1c47:d42:42:42:1080:1050"
  bgp:
    asn: 4242421050
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.atl1.routedbits.com:51080
  wg_pubkey: QKK4a4vZQ4sd6EdXZ2IIlXNoUVMqcWX8nGoKEfy/VGU=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
