wg_peers:
- name: dn42dal-gatuno
  port: 50180
  remote: "bokbok.gatuno.mx:50180"
  wg_pubkey: "sORFj7pR8ZO1U4vZxmgq0ue9gGGNf8wdrgr7kb+CTBA="
  peer_v4: "172.22.122.15"
  peer_v6: "fd42:470:f0ef:307::1/64"
  local_v6: "fd42:470:f0ef:307::2/64"

- name: dn42atl-napster
  port: 51050
  remote: atl1-us.dn42.napshome.net:51080
  wg_pubkey: "Cro0O53QVO63240SyAu1vkF7kOa/KeMIwT8+7qGV9lI="
  peer_v4: "172.22.169.128"
  peer_v6: "fda9:26a9:1c47:d42:42:42:1080:1050"

- name: dn42hsv-hfuller
  port: 51289
  remote: hsv-rtr.network.pixilic.com:30080
  wg_pubkey: "IKEynXwzlR5CY+XrklI/vsH97MfY1aqnQ8oiQ6AyHGU="
  peer_v4: "172.23.193.143"
  peer_v6: "fd7c:3727:9426:193::3"

- name: dn42-androw
  peer_v4: 172.23.186.36
  peer_v6: fe80::2575:4
  port: 22575
  remote: mks1.us.androw.eu:21080
  wg_pubkey: 7tBgRZZFJWmTAy36h4saz77BxXacCzes9KXgZew7Dns=

- name: dn42-mtzfederic
  remove: true

- name: dn42-exabyte
  remove: true

- name: dn42-nullplane
  remove: true

- name: dn42-imlonghao
  port: 21888
  remote: us1.dn42.ni.sb:21080
  wg_pubkey: uVIBY5keaBLtkT7oyD/W/TgEBiXerr/IPxtH+JO0amI=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888

- name: dn42-bri
  port: 22825
  remote: evo.pve.ibeep.com:21080
  wg_pubkey: ZB4ykdUcm3vNX23qFEHSiO7eQfyC5BoGbg9fHZGe/zE=
  peer_v4: null
  peer_v6: fe80::2825:2

- name: dn42-lare
  port: 23035
  remote: use1.dn42.lare.cc:21080
  wg_pubkey: FIcJb2vGsj10rUICV6Awp+/mGXi9L6lpIvQvblBVoQ0=
  peer_v4: null
  peer_v6: fe80::3035:136

- name: dn42-routedbits
  port: 20207
  remote: router.atl1.routedbits.com:51080
  wg_pubkey: QKK4a4vZQ4sd6EdXZ2IIlXNoUVMqcWX8nGoKEfy/VGU=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-zdong
  port: 22354
  remote: fl1-us.zdong.me:21080
  wg_pubkey: u9NcC04pptIt8ELgSrxZjHRKARvjfiaJuVR/rsdtYHE=
  peer_v4: 172.23.132.130
  peer_v6: fe80::2354
