wg_peers:
- name: igp-yvrlab
  port: 19999
  wg_pubkey: "5UUM0BZBvE5+/JDQtqPPLxPmpI+5prg/YfmvNzUbKnc="
  peer_v4: null
  local_v4: 172.22.108.78/31
  peer_v6: fe80::e545:cd0:1641:bc4e

- name: igp-glass
  remove: true
- name: igp-stub-glass
  port: 19998
  wg_pubkey: qqFf8jOa55jQT5R013iOStnaklrB9mHrVNCerLXhcg0=
  remote: glass.srv.jlu5.com:19998
  peer_v4: null
  local_v4: 172.22.108.65/30
  peer_v6: fe80::1080:1080

- name: "dn42atl-doxz"
  port: 50003
  remote: "45.76.249.17:51822"
  wg_pubkey: "2RkCWgwBkoq5jJhjDWI15nCxwgb6oQxdY9lIO18KEzs="
  peer_v4: "172.22.159.60/32"
  peer_v6: "fdfc:694e:234f::3/128"
  local_v6: "fd86:bad:11b7::1"

- name: dn42mci-aftbit
  port: 50822
  remote: "dn42.aftbit.com:51080"
  wg_pubkey: "JBj2+QjkQwFjBn/QRRVB2RWAw9mwC2Efev8AX2uMoUY="
  peer_v4: "172.23.222.129"
  peer_v6: "fe80::100"

- name: dn42chi-ncw
  port: 51288
  remote: "chi2.sc00.org:21080"
  wg_pubkey: "750WkOmYTh+gfrod2LRgKU46nkEJrWK2z6emynV+j3U="
  peer_v4: "172.20.233.129"
  peer_v6: "fe80::1288/64"

- name: dn42oma-zane
  port: 53315
  remote: "63.227.145.132:51080"
  wg_pubkey: "7SAw34vmYtgyEi05f78nc5kbEiCGvVTeqa3xdN+0034="
  peer_v4: "172.22.167.67"
  peer_v6: "fd62:e667:840a::2"
  local_v6: "fd86:bad:11b7::1"

- name: dn42-tech9
  peer_v4: 172.20.16.139
  peer_v6: fe80::1588
  port: 21588
  remote: us-chi01.dn42.tech9.io:51933
  wg_pubkey: 0kb8ffMcbx8oXZ3Ii5khOuCzmRqM2Cy0IslmrWtRGSk=
  local_v6: fe80::100

- name: dn42-lare
  port: 23035
  remote: use2.dn42.lare.cc:21080
  wg_pubkey: AREskFoxP2cd6DXoJ7druDsiWKX+8TwrkQqfi4JxRRw=
  peer_v4: null
  peer_v6: fe80::3035:137

- name: dn42-ventilaar
  port: 22246
  remote: atl04.dn42.ventilaar.net:31080
  wg_pubkey: qJQiON85WYvdMBHDu0T0rBKGYNexlPvQjtjkx/YNK2o=
  peer_v4: null
  peer_v6: fe80::2246

- name: dn42-ghoul
  port: 22975
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64653065633938366564383136626239336637343263646437316238633364393930616433663333
    3434303138396538313765633239336264656166626130390a346633326365303236303064396432
    33316537643930336166656365313564303935396130383763353163333934383032626236396239
    3361373632336136650a303034383839623439613135393930303938323130303834653962326436
    65656664343637313166343735336139633332323933313237666638323161386534
  wg_pubkey: KgG4Ycxde1/lkyIQzLPnhPofZv0lwd2r8UeLULS5tRw=
  peer_v4: 172.23.72.33
  peer_v6: fdb1:202a:f806:1::1

- name: dn42-routedbits
  port: 20207
  remote: router.chi1.routedbits.com:51080
  wg_pubkey: 89xUzROs3l/KNPLxDTJz4l5aEH1cmLb22bNgChhRiQo=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-c4tg
  remove: true

- name: dn42-bandura
  remove: true
