wg_peers:
- name: igp-yvrlab
  port: 19999
  wg_pubkey: "5UUM0BZBvE5+/JDQtqPPLxPmpI+5prg/YfmvNzUbKnc="
  peer_v4: null
  local_v4: 169.254.108.78/31
  peer_v6: fe80::e545:cd0:1641:bc4e

- name: dn42-doxz
  port: 50003
  remote: "45.76.249.17:51822"
  wg_pubkey: "2RkCWgwBkoq5jJhjDWI15nCxwgb6oQxdY9lIO18KEzs="
  peer_v4: "172.22.159.60/32"
  peer_v6: "fdfc:694e:234f::3/128"
  local_v6: fd86:bad:11b7::1
  bgp:
    asn: 4242422904
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-nicholascw
  port: 51288
  remote: "chi2.sc00.org:21080"
  wg_pubkey: "750WkOmYTh+gfrod2LRgKU46nkEJrWK2z6emynV+j3U="
  peer_v4: "172.20.233.129"
  peer_v6: "fe80::1288/64"
  bgp:
    asn: 4242421288
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-tech9
  peer_v4: 172.20.16.139
  peer_v6: fe80::1588
  port: 21588
  remote: us-chi01.dn42.tech9.io:51933
  wg_pubkey: 0kb8ffMcbx8oXZ3Ii5khOuCzmRqM2Cy0IslmrWtRGSk=
  local_v6: fe80::100
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-lare
  port: 23035
  remote: use2.dn42.lare.cc:21080
  wg_pubkey: AREskFoxP2cd6DXoJ7druDsiWKX+8TwrkQqfi4JxRRw=
  peer_v4: null
  peer_v6: fe80::3035:137
  bgp:
    asn: 4242423035
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
    export_mode: prepend

- name: dn42-ventilaar
  port: 22246
  remote: atl04.dn42.ventilaar.net:31080
  wg_pubkey: qJQiON85WYvdMBHDu0T0rBKGYNexlPvQjtjkx/YNK2o=
  peer_v4: null
  peer_v6: fe80::2246
  bgp:
    asn: 4242422246
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.chi1.routedbits.com:51080
  wg_pubkey: 89xUzROs3l/KNPLxDTJz4l5aEH1cmLb22bNgChhRiQo=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cdubs
  port: 20566
  remote: dn03.il.surgebytes.com:31080
  wg_pubkey: 8gIe+qsImuoxkQhjyX/6BmkI+H6A8nuAg6gfDZVTV1E=
  peer_v4: null
  peer_v6: fe80::566:3
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sdubs
  port: 20202
  remote: dn01.il.us.sdubs.vip:21080
  wg_pubkey: Y9WXsLsmsSeyEIUj2ibVfQblBduMfTBej/MIzj9BrAE=
  peer_v4: null
  peer_v6: fe80::202:1
  bgp:
    asn: 4242420202
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-gatuno
  port: 20180
  remote: bokbok.gatuno.mx:21080
  wg_pubkey: sORFj7pR8ZO1U4vZxmgq0ue9gGGNf8wdrgr7kb+CTBA=
  peer_v4: 172.22.122.15
  peer_v6: fe80::0180
  bgp:
    asn: 4242420180
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-9pfs
  port: 22002
  remote: null
  wg_pubkey: /ejtL+zL6PGhwczGDXiBL0PoVxLk+K3YMAArwc+tcyI=
  peer_v4: null
  peer_v6: fe80::2002:2
  bgp:
    asn: 4242422002
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-scoopta
  port: 21197
  remote: ninym.uwu.academy:11080
  wg_pubkey: vKYOjO3D/liyslRdvKHEwfUnAzMR19OM5gku7eKrJDc=
  peer_v4: null
  peer_v6: fe80::1197
  bgp:
    asn: 4242421197
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-kitauji
  port: 22314
  remote: 195.252.199.45:41080
  wg_pubkey: 7QUBU6NIaG82IZA6ft9KGKkIQzahm1/MsJCMNQvbYGQ=
  peer_v4: 172.22.179.97
  peer_v6: fe80::1747
  bgp:
    asn: 4242422314
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-joenet
  port: 20157
  remote: chi01.ke8jwh.com:31080
  wg_pubkey: PfhGU0DMRu5Wnf0JfNQnnOWpyiqNjZ+wUCG2p6zwui8=
  peer_v4: null
  peer_v6: fe80::157:234
  bgp:
    asn: 4242420157
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-stepnem
  port: 21282
  remote: us-nyc1.dn42.smrk.net:21080
  wg_pubkey: 3oEmrr4/Wi1c46CZI1HcnJcMw4cj76AmzMvxnL6N/S8=
  peer_v4: null
  peer_v6: fe80::1282
  bgp:
    asn: 4242421282
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-xeiu
  port: 21336
  remote: us1.dn42.xeiu.top:21080
  wg_pubkey: sAPnDL1pMJWffe//iG9E12d4IEF6BbSlLR2o9z9wDAg=
  peer_v4: 172.20.159.2
  peer_v6: fe80::1:1336
  bgp:
    asn: 4242421336
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-be0ba
  port: 20224
  remote: chi01.dn42.tcp80.org:40018
  wg_pubkey: dm2ju2/9CJeDm27hqS7WWoutmz49uksaSA4Me0S91nw=
  peer_v4: null
  peer_v6: fe80::224
  bgp:
    asn: 4242420224
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-iedon
  port: 22189
  remote: us-nyc.dn42.iedon.net:60608
  wg_pubkey: 2Wmv10a9eVSni9nfZ7YPsyl3ZC5z7vHq0sTZGgk5WGo=
  peer_v4: null
  peer_v6: fe80::2189:124
  bgp:
    asn: 4242422189
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-tatk
  port: 23152
  remote: rt0.us.tatk.network:21080
  wg_pubkey: 54tB3QacxF+NIfAZlXzwPsUuu23Z45TgQNmZMiuDFWo=
  peer_v4: null
  peer_v6: fe80::3152:4
  bgp:
    asn: 4242423152
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-badaimweeb
  port: 23797
  remote: us-ord1.rc.badaimweeb.me:5606
  wg_pubkey: sICZNWk3fJyETJkXWHmnxvUW6TEj+xh+xBjpZbKy23w=
  peer_v4: null
  peer_v6: fe80::3797
  bgp:
    asn: 4242423797
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
