wg_peers:
- name: igp-yvrlab
  port: 19999
  wg_pubkey: "5UUM0BZBvE5+/JDQtqPPLxPmpI+5prg/YfmvNzUbKnc="
  peer_v4: null
  local_v4: 169.254.108.78/31
  peer_v6: fe80::e545:cd0:1641:bc4e

- name: "dn42atl-doxz"
  port: 50003
  remote: "45.76.249.17:51822"
  wg_pubkey: "2RkCWgwBkoq5jJhjDWI15nCxwgb6oQxdY9lIO18KEzs="
  peer_v4: "172.22.159.60/32"
  peer_v6: "fdfc:694e:234f::3/128"
  bgp:
    asn: 4242422904
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-nicholascw
  port: 51288
  remote: "chi2.sc00.org:21080"
  wg_pubkey: "750WkOmYTh+gfrod2LRgKU46nkEJrWK2z6emynV+j3U="
  peer_v4: "172.20.233.129"
  peer_v6: "fe80::1288/64"
  bgp:
    asn: 4242421288
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-tech9
  peer_v4: 172.20.16.139
  peer_v6: fe80::1588
  port: 21588
  remote: us-chi01.dn42.tech9.io:51933
  wg_pubkey: 0kb8ffMcbx8oXZ3Ii5khOuCzmRqM2Cy0IslmrWtRGSk=
  local_v6: fe80::100
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true
    export_mode: prepend

- name: dn42-lare
  port: 23035
  remote: use2.dn42.lare.cc:21080
  wg_pubkey: AREskFoxP2cd6DXoJ7druDsiWKX+8TwrkQqfi4JxRRw=
  peer_v4: null
  peer_v6: fe80::3035:137
  bgp:
    asn: 4242423035
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
    import_mode: peer_only
    export_mode: prepend

- name: dn42-ventilaar
  port: 22246
  remote: atl04.dn42.ventilaar.net:31080
  wg_pubkey: qJQiON85WYvdMBHDu0T0rBKGYNexlPvQjtjkx/YNK2o=
  peer_v4: null
  peer_v6: fe80::2246
  bgp:
    asn: 4242422246
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.chi1.routedbits.com:51080
  wg_pubkey: 89xUzROs3l/KNPLxDTJz4l5aEH1cmLb22bNgChhRiQo=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cdubs
  port: 20566
  remote: dn03.il.surgebytes.com:31080
  wg_pubkey: 8gIe+qsImuoxkQhjyX/6BmkI+H6A8nuAg6gfDZVTV1E=
  peer_v4: null
  peer_v6: fe80::566:3
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sdubs
  port: 20202
  remote: dn01.il.us.sdubs.vip:21080
  wg_pubkey: Y9WXsLsmsSeyEIUj2ibVfQblBduMfTBej/MIzj9BrAE=
  peer_v4: null
  peer_v6: fe80::202:1
  bgp:
    asn: 4242420202
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

# BEGIN peers imported from dal.peer (202408)

- name: dn42-bandura
  port: 22923
  remote: aurora.mk16.de:51080
  wg_pubkey: bdV11rHcf1YIesd7y5UFyChr9+ZJ+0LtoblBXAlHzDs=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65373033623433623230613061633865613562633438393866383061633030363233373062303763
    3762643439643234316361666165336436383636306362310a333530336263393835353436393037
    33633035393837333837303865373633643361613535653132623238663336353734373939633733
    6135393935333530640a373363386530396634303732623139353062393261333739653666333365
    30306262343131386334343963633432353238336234616266383163366437396266623166353236
    3038366232633135323634343662663835366162346464376631
  local_v6: fe80::1080:33
  wg_privkey: /etc/wireguard/privatekey_dal
  bgp:
    asn: 4242422923
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-gatuno
  port: 20180
  remote: "bokbok.gatuno.mx:50180"
  wg_pubkey: "sORFj7pR8ZO1U4vZxmgq0ue9gGGNf8wdrgr7kb+CTBA="
  peer_v4: "172.22.122.15"
  peer_v6: "fd42:470:f0ef:307::1/64"
  local_v6: "fd42:470:f0ef:307::2/64"
  local_v4: 172.22.108.33
  wg_privkey: /etc/wireguard/privatekey_dal
  bgp:
    asn: 4242420180
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

# END peers imported from dal.peer

# BEGIN peers imported from atl/tpa (202408)
- name: dn42-napsterbat
  port: 51050
  remote: atl1-us.dn42.napshome.net:51080
  wg_pubkey: "Cro0O53QVO63240SyAu1vkF7kOa/KeMIwT8+7qGV9lI="
  peer_v4: "172.22.169.128"
  peer_v6: "fda9:26a9:1c47:d42:42:42:1080:1050"
  local_v4: 172.20.229.119
  local_v6: fd86:bad:11b7:9::1
  wg_privkey: /etc/wireguard/privatekey_atl
  bgp:
    asn: 4242421050
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-bri
  port: 22825
  remote: evo.pve.ibeep.com:21080
  wg_pubkey: ZB4ykdUcm3vNX23qFEHSiO7eQfyC5BoGbg9fHZGe/zE=
  peer_v4: null
  peer_v6: fe80::2825:2
  local_v6: fe80::1080:119
  wg_privkey: /etc/wireguard/privatekey_atl
  bgp:
    asn: 4242422825
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-zdong
  port: 22354
  remote: fl1-us.zdong.me:21080
  wg_pubkey: u9NcC04pptIt8ELgSrxZjHRKARvjfiaJuVR/rsdtYHE=
  peer_v4: 172.23.132.130
  peer_v6: fe80::2354
  local_v4: 172.20.229.119
  local_v6: fe80::1080:119
  wg_privkey: /etc/wireguard/privatekey_atl
  bgp:
    asn: 4242422354
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true
# END peers imported from tpa.peer

- name: dn42-9pfs
  port: 22002
  remote: null
  wg_pubkey: /ejtL+zL6PGhwczGDXiBL0PoVxLk+K3YMAArwc+tcyI=
  peer_v4: null
  peer_v6: fe80::2002:2
  bgp:
    asn: 4242422002
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-scoopta
  port: 21197
  remote: ninym.uwu.academy:11080
  wg_pubkey: vKYOjO3D/liyslRdvKHEwfUnAzMR19OM5gku7eKrJDc=
  peer_v4: null
  peer_v6: fe80::1197
  bgp:
    asn: 4242421197
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-kitauji
  port: 22314
  remote: 195.252.199.45:41080
  wg_pubkey: 7QUBU6NIaG82IZA6ft9KGKkIQzahm1/MsJCMNQvbYGQ=
  peer_v4: 172.22.179.97
  peer_v6: fe80::1747
  bgp:
    asn: 4242422314
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-joenet
  port: 20157
  remote: chi01.ke8jwh.com:31080
  wg_pubkey: PfhGU0DMRu5Wnf0JfNQnnOWpyiqNjZ+wUCG2p6zwui8=
  peer_v4: null
  peer_v6: fe80::157:234
  bgp:
    asn: 4242420157
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-stepnem
  port: 21282
  remote: us-nyc1.dn42.smrk.net:21080
  wg_pubkey: 3oEmrr4/Wi1c46CZI1HcnJcMw4cj76AmzMvxnL6N/S8=
  peer_v4: null
  peer_v6: fe80::1282
  bgp:
    asn: 4242421282
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
