wg_peers:
- name: dn42-tech9
  peer_v4: 172.20.16.140
  peer_v6: fe80::1588
  port: 21588
  remote: us-dal01.dn42.tech9.io:59321
  wg_pubkey: iEZ71NPZge6wHKb6q4o2cvCopZ7PBDqn/b3FO56+Hkc=
  local_v6: fe80::100

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030:14
  port: 22717
  remote: us.vm.whojk.com:23001
  wg_pubkey: lhWFk53u42PlQ+P7QkBJt1+tXTc/H0EE/FwdBYkTcGY=

- name: dn42-c4tg
  peer_v4: null
  peer_v6: fe80::4242
  port: 21411
  remote: null
  wg_pubkey: U8TI9G8zHFuCnzsDgclhFtNHhqfHG/1DoC8O3OFBfFo=

- name: dn42-bandura
  port: 22923
  remote: aurora.mk16.de:51080
  wg_pubkey: bdV11rHcf1YIesd7y5UFyChr9+ZJ+0LtoblBXAlHzDs=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65373033623433623230613061633865613562633438393866383061633030363233373062303763
    3762643439643234316361666165336436383636306362310a333530336263393835353436393037
    33633035393837333837303865373633643361613535653132623238663336353734373939633733
    6135393935333530640a373363386530396634303732623139353062393261333739653666333365
    30306262343131386334343963633432353238336234616266383163366437396266623166353236
    3038366232633135323634343662663835366162346464376631

- name: dn42-routedbits
  port: 20207
  remote: router.dal1.routedbits.com:51080
  wg_pubkey: 8clbJPxK5ylOhFDNGdn/CL5zRWQdf7rXbLeF7j8czFI=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-gatuno
  port: 20180
  remote: "bokbok.gatuno.mx:50180"
  wg_pubkey: "sORFj7pR8ZO1U4vZxmgq0ue9gGGNf8wdrgr7kb+CTBA="
  peer_v4: "172.22.122.15"
  peer_v6: "fd42:470:f0ef:307::1/64"
  local_v6: "fd42:470:f0ef:307::2/64"

- name: dn42-imlonghao
  port: 21888
  remote: us3.dn42.ni.sb:21080
  wg_pubkey: dAL/VWmLLXKhum3S82INvBmXizID6/51RgdGBkD/M1g=
  wg_mtu: 1296
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888
