wg_peers:
- name: dn42-tech9
  peer_v4: 172.20.16.140
  peer_v6: fe80::1588
  port: 21588
  remote: us-dal01.dn42.tech9.io:59321
  wg_pubkey: iEZ71NPZge6wHKb6q4o2cvCopZ7PBDqn/b3FO56+Hkc=
  local_v6: fe80::100
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false
    export_mode: prepend

- name: dn42-bandura
  port: 22923
  remote: aurora.mk16.de:51080
  wg_pubkey: bdV11rHcf1YIesd7y5UFyChr9+ZJ+0LtoblBXAlHzDs=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65373033623433623230613061633865613562633438393866383061633030363233373062303763
    3762643439643234316361666165336436383636306362310a333530336263393835353436393037
    33633035393837333837303865373633643361613535653132623238663336353734373939633733
    6135393935333530640a373363386530396634303732623139353062393261333739653666333365
    30306262343131386334343963633432353238336234616266383163366437396266623166353236
    3038366232633135323634343662663835366162346464376631
  bgp:
    asn: 4242422923
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.dal1.routedbits.com:51080
  wg_pubkey: 8clbJPxK5ylOhFDNGdn/CL5zRWQdf7rXbLeF7j8czFI=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

# BEGIN peers imported from atl (202408)
- name: dn42-napsterbat
  port: 51050
  remote: atl1-us.dn42.napshome.net:51080
  wg_pubkey: "Cro0O53QVO63240SyAu1vkF7kOa/KeMIwT8+7qGV9lI="
  peer_v4: "172.22.169.128"
  peer_v6: "fda9:26a9:1c47:d42:42:42:1080:1050"
  local_v4: 172.20.229.119
  local_v6: fd86:bad:11b7:9::1
  wg_privkey: /etc/wireguard/privatekey_atl
  bgp:
    asn: 4242421050
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true
# END peers imported from atl

- name: dn42-be0ba
  port: 20224
  remote: dal01.dn42.tcp80.org:40015
  wg_pubkey: 3T1a4znEbtN20C5GGGpSgibHHzqx79OPjCmLtxytbw0=
  peer_v4: null
  peer_v6: fe80::224
  bgp:
    asn: 4242420224
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
