wg_peers:
- name: dn42-tech9
  peer_v4: 172.20.16.140
  peer_v6: fe80::1588
  port: 21588
  remote: us-dal01.dn42.tech9.io:59321
  wg_pubkey: iEZ71NPZge6wHKb6q4o2cvCopZ7PBDqn/b3FO56+Hkc=
  local_v6: fe80::100
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-bandura
  port: 22923
  remote: aurora.mk16.de:51080
  wg_pubkey: bdV11rHcf1YIesd7y5UFyChr9+ZJ+0LtoblBXAlHzDs=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65373033623433623230613061633865613562633438393866383061633030363233373062303763
    3762643439643234316361666165336436383636306362310a333530336263393835353436393037
    33633035393837333837303865373633643361613535653132623238663336353734373939633733
    6135393935333530640a373363386530396634303732623139353062393261333739653666333365
    30306262343131386334343963633432353238336234616266383163366437396266623166353236
    3038366232633135323634343662663835366162346464376631
  bgp:
    asn: 4242422923
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.dal1.routedbits.com:51080
  wg_pubkey: 8clbJPxK5ylOhFDNGdn/CL5zRWQdf7rXbLeF7j8czFI=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-be0ba
  port: 20224
  remote: dal01.dn42.tcp80.org:40015
  wg_pubkey: 3T1a4znEbtN20C5GGGpSgibHHzqx79OPjCmLtxytbw0=
  peer_v4: null
  peer_v6: fe80::224
  bgp:
    asn: 4242420224
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-prefixlabs
  port: 21240
  remote: us-02.prefixlabs.net:21080
  wg_pubkey: +NrpWdvnG57iyu5nNUMRLlMGAScyibhjGy1Ev4NbhgI=
  peer_v4: 172.20.209.12
  peer_v6: fe80::1240:3
  bgp:
    asn: 4242421240
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-cowgl
  port: 23999
  remote: slc.node.cowgl.xyz:31080
  wg_pubkey: rxicmyDFnBh33mW/EfG0VGXE/yxB5YmBcuWfyntg9Xk=
  peer_v4: 172.22.144.70
  peer_v6: "fd36:62be:ef51:6::1"
  bgp:
    asn: 4242423999
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false
