wg_peers:
- name: dn42ams-jrb0001
  port: 50119
  remote: "95.179.134.138:21080"
  wg_pubkey: "hwEFCjMf4xzaXzsmk4JdPllJjuxC3r7UPjL632A+L3M="
  peer_v4: "172.20.1.1"
  peer_v6: "fe80::119"

- name: dn42ams-aureus
  port: 50007
  remote: "s.hanfucw.com:8558"
  wg_pubkey: "ViMRAXJbz8rxqiXUljsx3gF0nLG9a612Qr6DllYLs3k="
  peer_v4: "10.127.8.185"
  peer_v6: "fd10:127:7::1"

- name: "dn42ams-tomkap"
  port: 52092
  remote: "nl0.dn42.pebkac.gr:51080"
  wg_pubkey: "g4MJv6qMPwbffxNjUKmIa5Yhf5ZzRqjIMzMHCSiFQgs="
  peer_v4: 172.21.67.200/32
  peer_v6: "fe80::42:1080:1/128"

- name: dn42fra-welterd
  port: 54738
  remote: "gate1.defra0.dn42.welterde.net:42002"
  wg_pubkey: "I68Jv8818pk2NX0GC8ul18095/iZ66XCxJuo/brk/Go="
  peer_v4: null
  peer_v6: "fe80::fcde:3558"

- name: dn42ams-yura
  port: 52464
  remote: "llix.dneo.moeternet.com:21080"
  wg_pubkey: "3egMh/fpa/+YTAfIXihtNYTReh27AaS53WJyp7UT/Qg="
  peer_v4: "172.20.191.207/32"
  peer_v6: "fe80::2464/64"

- name: dn42osl-yurui
  port: 52330
  remote: "osl01.kn.node.argonauts.xyz:51080"
  wg_pubkey: "POZ2ZRRPbQtfcb1d0eiNeKlBVqJiYFQ4/naY/xfkfDQ="
  peer_v4: "172.23.32.3"
  peer_v6: "fe80::2330:1"

- name: dn42ams-mayli
  port: 51123
  remote: "ams.ccp.ovh:21080"
  wg_pubkey: "e5X1ZlZUOVtTFeWi+d6cUqqNaXB0F2UHwbquAKU4z3I="
  peer_v4: "172.20.47.2"
  peer_v6: "fe80::1123"

- name: dn42ams-camelus
  port: 21592
  remote: "nl01.dn42.trampel.org:41080"
  wg_pubkey: "RcXm6OK+3+/sjXoivNTdjU3W5ctdohZ9GKYS25f05n8="
  peer_v4: "172.21.99.189"
  peer_v6: "fe80::1592"

- name: dn42dus-tsingya
  port: 23699
  remote: "dus-de.tsingyao.pub:21080"
  wg_pubkey: "xyhzHBpNDQlyeNG44xaU5zz86+Qeig8v6/PTutZqCRM="
  peer_v4: "172.22.155.9"
  peer_v6: "fe80::42:3699:9"

- name: dn42prg-wg
  port: 22331
  remote: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64646433373431313533623962626635303161653437306335303337393430353431373566626130
          3835316463646631613266363139336638363130396134390a653137663236343639623334663437
          36333962386339343033663962363461396535323963303035363364393330663931626636613931
          6437346437303264620a633363653965656331386163333263316639613436376633336466383962
          62653433383734323130396566333735346465346338633839343134303336616134
  wg_pubkey: "22Yg+PozQDDJUufe2POaV/ron0wZ6LVznpMgrRZDAXI="
  peer_v4: null
  peer_v6: "fe80::2331"

- name: dn42mow-dgy
  port: 20826
  remote: "ru.dn42.dgy.xyz:21080"
  wg_pubkey: "Y8E2cd2DKr7hZ3qs1WgU+2l+qWHaOxw4vFPAGevpiW0="
  peer_v4: null
  peer_v6: "fe80::826"

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030:c
  port: 22717
  remote: nl.vm.whojk.com:23010
  wg_pubkey: cokP4jFBH0TlBD/m3sWCpc9nADLOhzM2+lcjAb3ynFc=

- name: dn42-iedon
  peer_v4: 172.23.91.125
  peer_v6: fe80::2189:e9
  port: 22189
  remote: de-fra.dn42.kuu.moe:58384
  wg_pubkey: FHp0OR4UpAS8/Ra0FUNffTk18soUYCa6NcvZdOgxY0k=

- name: dn42-bling
  peer_v4: 172.20.21.106
  peer_v6: fe80::2333
  port: 20212
  remote: ams1.dn42.blw.moe:21080
  wg_pubkey: HXF4JPhmBCYL/e/mjdvxyiII8WchPQLK8AUVwTNPe3Q=

- name: dn42-haojunmei
  peer_v4: 172.23.114.17
  peer_v6: fe80::1145
  port: 23663
  remote: nl-amsterdam-01.dn42.yunyingstudio.cn:21080
  wg_pubkey: b0SqBBmXh/A7Ksag5ZT/rtqGL3HchRXcPuHwdTfBrC0=

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: eu-west1.dn42.huajitech.net:21080
  wg_pubkey: dDM/rtklvpKHeIOKeLGjfYBTl+jEuhlr7dMIOdXbliU=

- name: dn42-spf
  peer_v4: 172.23.24.33
  peer_v6: fe80::ade1
  port: 21964
  remote: nl1.dn42.southparkfan.org:21964
  wg_pubkey: OBpyD/rruK4pOCgRVrWVoexBNHZadtn4qwPmrEjt0gY=

### BEGIN peers imported from de-nbg01
- name: dn42nbg-w1kl4s
  port: 51516
  remote: "ichaival.dn42.chris.symphogear.network:51080"
  wg_pubkey: "zNP632K1qrezFIl8NQK1tR3XEdYHat/YgzdCXnFIWDE="
  peer_v4: "172.23.193.2"
  peer_v6: "fe80::b0b6/64"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fsn-tbspace
  port: 56190
  remote: "dn42.tbspace.de:49047"
  wg_pubkey: "Q4cHTtTYBJY0jq3phMdgDM4/ijHRht+vQNB7L2NeZnM="
  peer_v4: "172.23.235.1"
  peer_v6: "fe80::1299:e"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42lux-lantian
  port: 52547
  remote: "buyvm.lantian.pub:21080"
  wg_pubkey: "DkmSBCIgrxPPZmT07DraoCSD/jSByjPkYqHJWfVZ5hM="
  peer_v4: "172.22.76.187"
  peer_v6: "fe80::2547"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-tech9
  port: 51588
  remote: "de-fra02.dn42.tech9.io:56614"
  wg_pubkey: "MD1EdVe9a0yycUdXCH3A61s3HhlDn17m5d07e4H33S0="
  peer_v4: "172.20.16.141"
  peer_v6: "fe80::1588/64"
  local_v6: "fe80::100"
  local_v4: "172.20.229.117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-kioubit
  port: 53914
  remote: "de2.g-load.eu:21080"
  wg_pubkey: "B1xSG/XTJRLd+GrWDsB06BqnIq8Xud93YVh/LYYYtUY="
  peer_v4: "172.20.53.97"
  peer_v6: "fe80::ade0"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-miegl
  port: 50181
  remote: "de-nue01.dn42.miegl.cz:31206"
  wg_pubkey: "gUG7Thru8TyS8pUVqBrR4Jt7AXpGMRj0VHZlb4I5GiE="
  peer_v4: "172.20.48.129"
  peer_v6: "fe80::181:1"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-moecast
  port: 50604
  remote: "de1.dn42.cas7.moe:21080"
  wg_pubkey: "1dJpFLegKHKButkXqbv1KLLMTmS6KtFkWBz6GRo2uxE="
  peer_v4: "172.23.89.3"
  peer_v6: "fe80::604:3"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-uffsalo
  port: 50780
  remote: "router.fra4.dn42.brand-web.net:41080"
  wg_pubkey: "7V65FxvD9AQetyUr0qSiu+ik8samB4Atrw2ekvC0xQM="
  peer_v4: "172.20.191.129"
  peer_v6: "fe80::780"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-maraun
  port: 52225
  remote: "37.120.175.249:51080"
  wg_pubkey: "uS1AYe7zTGAP48XeNn0vppNjg7q0hawyh8Y0bvvAWhk="
  peer_v4: "172.20.12.196"
  peer_v6: "fe80::42:4242:2225"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-rhmn
  port: 50807
  remote: "dn42-de1.rhmn.io:21080"
  wg_pubkey: "Z3hd+ogID0pOUwJTyGQV7RBoGh0JBpe7ZOD7lJ63JWg="
  peer_v4: "172.21.67.65"
  peer_v6: "fe80::65"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-sunnet
  port: 53088
  remote: "fra1-de.dn42.6700.cc:21080"
  wg_pubkey: "TWQhJYK+ynNz7A4GMAQSHAyUUKTnAYrBfWTzzjzhAFs="
  peer_v4: "172.21.100.195/32"
  peer_v6: "fe80::3088:195/64"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42kiv-gfa
  port: 51097
  remote: "dn42-md-1.4679.ar:51821"
  wg_pubkey: "Ta3fZ2A2FVhyD6cOzXdqF5zo0mYG5x9pmFJPbI6p8X4="
  peer_v4: "172.21.68.1"
  peer_v6: "fe80::1:100/64"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: "dn42fra-munster"
  port: 52237
  remote: "de-fra01.dn42.munsternet.eu:21080"
  wg_pubkey: "p8SOiZ+EN6DOHVUbBb/kUiq81Uu006Xrz0B55W+fqDg="
  peer_v4: null
  peer_v6: "fe80::42:2237/128"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-burble
  port: 22601
  remote: "dn42-de-fra1.burble.com:21080"
  wg_pubkey: "e85ftjKwgZCu5Zfx8chHY/LYJSwTbTqX3tbSqViX7Xo="
  peer_v4: "172.20.129.169"
  peer_v6: "fd42:4242:2601:31::1/128"
  local_v4: "172.20.229.117"
  local_v6: "fd86:bad:11b7:117::1"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fra-napster
  port: 51050
  remote: ffm1-de.dn42.napshome.net:51080
  wg_pubkey: "uo7tLeb1QNoRJtecjUV4TeNYgw2imd11oLx7Hftg2SM="
  peer_v4: "172.22.169.141"
  peer_v6: "fda9:26a9:1c47:1d42:42:42:1080:1050"
  local_v4: "172.20.229.117"
  local_v6: "fd86:bad:11b7:117::1"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-fixmix
  port: 51876
  remote: "157.90.166.124:21080"
  wg_pubkey: "rlfzxSL24UfKvl3cZsHcUr+i3MtG13tu8PRdDqOX3A0="
  peer_v4: "172.22.66.59"
  peer_v6: "fe80::1876"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42rhr-n0emis
  port: 50197
  remote: "himalia.dn42.n0emis.eu:51080"
  wg_pubkey: "ObF+xGC6DdddJer0IUw6nzC0RqzeKWwEiQU0ieowzhg="
  peer_v4: "172.20.190.96"
  peer_v6: "fe80::42:42:1"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-serverm
  port: 53770
  remote: "nbg1.dn42.servermade.com:51080"
  wg_pubkey: "iM2wCf6z5DnzeI4QufFima+slsPloQXccnLygeSTDmA="
  peer_v4: "172.22.118.134"
  peer_v6: "fe80::3770/64"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-plasma
  port: 52322
  remote: "85.10.202.194:42235"
  wg_pubkey: "g4jQ1g2pYk2mXQhuDNL7E6zHqkcLpqS+YxdMAnAAo3w="
  peer_v4: 172.22.181.193
  peer_v6: fd42:4242:2322::1
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-hax404
  port: 50428
  remote: "jlu5.peers.hax404.de:42023"
  wg_pubkey: "jhBOiTGmvmyp1g3T7FwLVeHMMsxBHgjTtbebdwnfIH0="
  peer_v4: "172.23.136.34"
  peer_v6: "fe80::404"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42fsn-foxxx0
  port: 23669
  remote: "valhalla.nano-srv.net:21080"
  wg_pubkey: "6xP06zR9g8lCD1zSxPDAjERI7mq+3M68dCUwVhJ5cEM="
  peer_v4: "172.22.169.194"
  peer_v6: "fe80::3669:1"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42nbg-thomas
  port: 22571
  remote: "dn42.tho.cloud:21080"
  wg_pubkey: "+yN2BB+jmJRSG3fA4tGNiT0iC277x0ae+4jvWt9nS0w="
  peer_v4: "172.20.42.148"
  peer_v6: "fe80::2571"
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42-kskb1817
  peer_v4: 172.22.77.42
  peer_v6: fe80::42:1817:a
  port: 21817
  remote: null
  wg_pubkey: Sxn9qXnzu3gSBQFZ0vCh5t5blUJYgD+iHlCCG2hexg4=
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42-186526
  peer_v4: 172.23.2.85
  peer_v6: fe80::ade1
  port: 23764
  remote: de-frankfurt-01.edge.186526.xyz:21080
  wg_pubkey: 1wMNeQ+QH3V7xme0P0IBbTrAuDD28iwcxBNIwhbO7Xs=
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42-pgnhd
  peer_v4: 172.23.86.32
  peer_v6: fe80::1078
  port: 21078
  remote: dn42.pgnhd.moe:3947
  wg_pubkey: 72yTeL6AEAmWKNYGc14mYSjYU9qElYLSMzxaNhSua08=
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42-hanlin
  peer_v4: 172.23.163.36
  peer_v6: fd88:1926:817:4::1
  port: 20251
  remote: lu.serv.hanlin.press:21080
  wg_pubkey: lYbabe1M2z7a2xyv/pbikTRdW4FWB3CPmc4MbeDBZ0A=
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

- name: dn42-lutoma
  peer_v4: 172.22.119.1
  peer_v6: fe80::acab
  port: 24719
  remote: de-fra.dn42.lutoma.org:42433
  wg_pubkey: uVeGQhyJZujiB7GozhV4wFuY8oeNOJ4zdRyo+qiSKyc=
  local_v4: "172.20.229.117"
  local_v6: "fe80::117"
  wg_privkey: "/etc/wireguard/privatekey_de-nbg01"

### END peers imported from de-nbg01

- name: dn42fra-zhaofen
  port: 21926
  remote: "[2a06:e881:5506::1]:21080"
  wg_pubkey: "Y/OkiTBx7Nkg/mmG7WnHrDY/UisV/M6FyHwr7mKNmEM="
  peer_v4: "172.20.16.2"
  peer_v6: "fe80::1926:1"

- name: dn42waw-filip
  port: 21404
  remote: "176.122.215.101:65001"
  wg_pubkey: "oZXF/BkUUpHDxgze+pYqSvoLv2JGkkemKSGWU9t3cWk="
  peer_v4: "172.20.178.65"
  peer_v6: "fe80::feec:daff:fe46:d60e/64"

- name: dn42fsn-qcore
  port: 23847
  remote: "de-flk-dn42.0011.de:21080"
  wg_pubkey: "fX/ulzytJkYMxr9P1pHlRpmyQ11oQ1EfpdUDpX6UnX8="
  peer_v4: null
  peer_v6: "fe80::42:3847:42:1080"

- name: dn42fsn-bastel
  port: 23668
  remote: "router01.bastelfreak.org:1080"
  wg_pubkey: "P9BQFIpN7LvgnqkU/1srErP1I0twhgkUgEHZfaF5vyQ="
  peer_v4: "169.254.0.3"
  peer_v6: "fe80::beef:8"

- name: dn42-claudweb
  peer_v4: 172.23.125.33
  peer_v6: fe80::1247
  port: 21147
  remote: dn42-de01.claudweb.de:21080
  wg_pubkey: whaUeLgjEZBsf4fVdunWntucu8FEqQbWbyT5N5VBMxE=

- name: dn42-dingemans
  peer_v4: 172.23.89.146
  peer_v6: fe80::3:349a
  port: 20074
  remote: dn42.dingemans.tk:51820
  wg_pubkey: 8qZ8e5XG6G1OE3F/yGTB7iCIvV9IouHzpf+cSyPadxY=

- name: dn42-ty3r0x
  peer_v4: 172.22.69.1
  peer_v6: fe80::2596
  port: 22596
  remote: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31343265313337316538663264656332336236643532613934373936663837326337353531633963
          6363663365353962346332383031333639356638336335310a353230333032623831633165643434
          63313030336331323962356238323035316134343434666539373034643535656462393062343165
          3166646432373563650a626132393437363163346432623831613739616364356366663831313932
          34393266363131346531306261653961336663316136306436666338393938663363
  wg_pubkey: QRORBRZgOAhh2g4BTEx2jHrejQ3HdJYqV5yJRCUsgBw=

- name: dn42-baiyu
  peer_v4: 172.23.221.65
  peer_v6: fe80::1901:2761:0:1
  port: 21901
  remote: node1.vultr.fra.europe.dn42.dalao-home.com:21080
  wg_pubkey: Fq441bovZ0RAmgGPn+bbd2xLht9Mbsgw5YCa5bFgsm0=

- name: dn42-techanit
  peer_v4: null
  peer_v6: fe80::2206
  port: 22206
  remote: de1.dn42.est-it.de:13237
  wg_pubkey: QqcsQ6gRaK0ZxRskCxWoNeV2vd53/9IW/XfwjMMSjk8=

- name: dn42-arisum
  peer_v4: 172.21.86.97
  peer_v6: fe80::c0fe
  port: 21557
  remote: de-nbg01.dn42.h-k.sk:51080
  wg_pubkey: sydPdyJNOxVlk+b5fGMXaDxTcGY/+lmlX4usMPIM9nk=

- name: dn42-oscrx
  peer_v4: null
  peer_v6: fd69:420:cafe::1
  port: 23818
  remote: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333136613963363534326231666332316138653639663733333565393064613735323630383137
          3664626230386532613166613633383162653564333032350a646563303338306564643637396333
          38326334316236343638333866343135366163373039306636323136633534333936666361646638
          3831356636613937610a623630613633653032333561336636623937303535393834663332353962
          37326236393661643637356430373931396530656665386534373137326166383464
  wg_pubkey: UDn35z45Uh9DxDL6zrHmFChjV0sYWlyPrwjUFe8ofTU=

- name: dn42-tmnet
  peer_v4: null
  peer_v6: fe80::cafe
  port: 23089
  remote: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66626638373330613830346563396630646132386233366130336135373931613033643533626462
          3230313238303763636133336532303234373636393335320a333639333365363462386231663634
          34623562326166376262646431393934626433336161646234383361323131636236613764666131
          3530393166633661350a393130653439656665323463313565613830303734383461393639373762
          66613637636331366163363037363534393135626638376432623561333935393839
  wg_pubkey: CpZ6YCfbGVIW56OZGUlqAtMRyiR4b+vMZaoyF+rbX0Y=
