wg_peers:
- name: dn42nbg-w1kl4s
  port: 51516
  remote: "ichaival.dn42.chris.symphogear.network:51080"
  wg_pubkey: "zNP632K1qrezFIl8NQK1tR3XEdYHat/YgzdCXnFIWDE="
  peer_v4: "172.23.193.2"
  peer_v6: "fe80::b0b6/64"

- name: dn42fsn-tbspace
  port: 56190
  remote: "dn42.tbspace.de:49047"
  wg_pubkey: "Q4cHTtTYBJY0jq3phMdgDM4/ijHRht+vQNB7L2NeZnM="
  peer_v4: "172.23.235.1"
  peer_v6: "fe80::1299:e"

- name: dn42lux-lantian
  port: 52547
  remote: "buyvm.lantian.pub:21080"
  wg_pubkey: "DkmSBCIgrxPPZmT07DraoCSD/jSByjPkYqHJWfVZ5hM="
  peer_v4: "172.22.76.187"
  peer_v6: "fe80::2547"

- name: dn42fra-tech9
  port: 51588
  remote: "de-fra02.dn42.tech9.io:56614"
  wg_pubkey: "MD1EdVe9a0yycUdXCH3A61s3HhlDn17m5d07e4H33S0="
  peer_v4: "172.20.16.141"
  peer_v6: "fe80::1588/64"
  local_v6: "fe80::100"

- name: dn42nbg-kioubit
  port: 53914
  remote: "de2.g-load.eu:21080"
  wg_pubkey: "B1xSG/XTJRLd+GrWDsB06BqnIq8Xud93YVh/LYYYtUY="
  peer_v4: "172.20.53.97"
  peer_v6: "fe80::ade0"

- name: dn42fra-uffsalo
  port: 50780
  remote: "router.fra4.dn42.brand-web.net:41080"
  wg_pubkey: "7V65FxvD9AQetyUr0qSiu+ik8samB4Atrw2ekvC0xQM="
  peer_v4: "172.20.191.129"
  peer_v6: "fe80::780"

- name: dn42nbg-maraun
  port: 52225
  remote: "37.120.175.249:51080"
  wg_pubkey: "uS1AYe7zTGAP48XeNn0vppNjg7q0hawyh8Y0bvvAWhk="
  peer_v4: "172.20.12.196"
  peer_v6: "fe80::42:4242:2225"

- name: dn42nbg-rhmn
  port: 50807
  remote: "dn42-de1.rhmn.io:21080"
  wg_pubkey: "Z3hd+ogID0pOUwJTyGQV7RBoGh0JBpe7ZOD7lJ63JWg="
  peer_v4: "172.21.67.65"
  peer_v6: "fe80::65"

- name: dn42fra-sunnet
  port: 53088
  remote: "fra1-de.dn42.6700.cc:21080"
  wg_pubkey: "TWQhJYK+ynNz7A4GMAQSHAyUUKTnAYrBfWTzzjzhAFs="
  peer_v4: "172.21.100.195/32"
  peer_v6: "fe80::3088:195/64"

- name: "dn42fra-munster"
  port: 52237
  remote: "de-fra01.dn42.munsternet.eu:21080"
  wg_pubkey: "p8SOiZ+EN6DOHVUbBb/kUiq81Uu006Xrz0B55W+fqDg="
  peer_v4: null
  peer_v6: "fe80::42:2237/128"

- name: dn42fra-burble
  port: 22601
  remote: "dn42-de-fra1.burble.com:21080"
  wg_pubkey: "e85ftjKwgZCu5Zfx8chHY/LYJSwTbTqX3tbSqViX7Xo="
  peer_v4: "172.20.129.169"
  peer_v6: "fd42:4242:2601:31::1/128"

- name: dn42fra-napster
  port: 51050
  remote: ffm1-de.dn42.napshome.net:51080
  wg_pubkey: "uo7tLeb1QNoRJtecjUV4TeNYgw2imd11oLx7Hftg2SM="
  peer_v4: "172.22.169.141"
  peer_v6: "fda9:26a9:1c47:1d42:42:42:1080:1050"

- name: dn42nbg-serverm
  port: 53770
  remote: "nbg1.dn42.servermade.com:51080"
  wg_pubkey: "iM2wCf6z5DnzeI4QufFima+slsPloQXccnLygeSTDmA="
  peer_v4: "172.22.118.134"
  peer_v6: "fe80::3770/64"

- name: dn42nbg-plasma
  port: 52322
  remote: "85.10.202.194:42235"
  wg_pubkey: "g4jQ1g2pYk2mXQhuDNL7E6zHqkcLpqS+YxdMAnAAo3w="
  peer_v4: 172.22.181.193
  peer_v6: fd42:4242:2322::1

- name: dn42nbg-hax404
  port: 50428
  remote: "jlu5.peers.hax404.de:42023"
  wg_pubkey: "jhBOiTGmvmyp1g3T7FwLVeHMMsxBHgjTtbebdwnfIH0="
  peer_v4: "172.23.136.34"
  peer_v6: "fe80::404"

- name: dn42fsn-foxxx0
  port: 23669
  remote: "valhalla.nano-srv.net:21080"
  wg_pubkey: "6xP06zR9g8lCD1zSxPDAjERI7mq+3M68dCUwVhJ5cEM="
  peer_v4: "172.22.169.194"
  peer_v6: "fe80::3669:1"

- name: dn42nbg-thomas
  port: 22571
  remote: "dn42.tho.cloud:21080"
  wg_pubkey: "+yN2BB+jmJRSG3fA4tGNiT0iC277x0ae+4jvWt9nS0w="
  peer_v4: "172.20.42.148"
  peer_v6: "fe80::2571"

- name: dn42-kskb1817
  port: 21817
  remote: null
  wg_pubkey: Sxn9qXnzu3gSBQFZ0vCh5t5blUJYgD+iHlCCG2hexg4=
  peer_v4: 172.22.77.42
  peer_v6: fe80::42:1817:a

- name: dn42-lutoma
  peer_v4: 172.22.119.1
  peer_v6: fe80::acab
  port: 24719
  remote: de-fra.dn42.lutoma.org:42433
  wg_pubkey: uVeGQhyJZujiB7GozhV4wFuY8oeNOJ4zdRyo+qiSKyc=

- name: dn42-imlonghao
  port: 21888
  remote: de1.dn42.ni.sb:21080
  wg_pubkey: k9F2akSTkbA/GiO59PNW/v0D65ioMYD4P1DqeKSL3FM=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888

- name: dn42-yura
  port: 22464
  remote: lux.dneo.moeternet.com:21080
  wg_pubkey: qIhJZf6mTruzO4GTCUrJnLqs9ID4TI1GctRhaRilBkg=
  peer_v4: null
  peer_v6: fe80::2464

- name: dn42-mirsal
  port: 22308
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30303732393464666263663066656431636234613965663831663639323230326464613437346263
    6431323135646636303563333434356433626338336161640a363563666263326533393231326330
    63613737333131636138613561383465616564666565616539613034663832663261323562356363
    6230643063363963340a366433376663613861366664323837623733616665313864343063376563
    38376330646434316639323539356439373763373135353265353566353766653234
  wg_pubkey: iXu4yUw4w8/+hEHsOoQg26lByH8FAStv2pUnA0IeeXw=
  peer_v4: null
  peer_v6: fe80::1080

- name: dn42-lare
  port: 23035
  remote: de01.dn42.lare.cc:42413
  wg_pubkey: OL2LE2feDsFV+fOC4vo4u/1enuxf3m2kydwGRE2rKVs=
  peer_v4: 172.22.125.130
  peer_v6: fe80::3035:130

- name: dn42-modzilla
  port: 21909
  remote: 23.88.107.9:51825
  wg_pubkey: x1rsNq2U+DVeQCbLLlh58gE+fJbNCeDi6q+4AW3EFHY=
  peer_v4: null
  peer_v6: fe80::9656:d128:8652:64b7

- name: dn42-c4tg
  peer_v4: null
  peer_v6: fe80::1411:1
  port: 21411
  remote: famfo.xyz:21080
  wg_pubkey: IsKZ+XQD2fq0thj3qWIOO9CH9jKDnDQABKcBzNU8JTM=

- name: dn42-caskd
  port: 20475
  remote: null
  wg_pubkey: /cHmTdDk94GA19FG5oT9Q8KYSHQnNHPPyJ2iUCuVjGU=
  peer_v4: null
  peer_v6: fe80::2

- name: dn42-e1mo
  port: 20565
  remote: dn42-nbg1.net.dont-break.it:21080
  wg_pubkey: 6w37ckKLGl6Bdt2PrGGqe+msMwvxniKLy4Efe1ICXi0=
  peer_v4: null
  peer_v6: fe80::565

- name: dn42-camelusfer
  port: 21592
  remote: de01.dn42.ca.melusfer.us:41080
  wg_pubkey: iMU/cowB17kYnBWktlT5H98J2mKRYf5v3PwsjWcNmR8=
  peer_v4: null
  peer_v6: fe80::1592
- name: dn42-routedbits
  port: 20207
  remote: router.fra1.routedbits.com:51080
  wg_pubkey: FIk95vqIJxf2ZH750lsV1EybfeC9+V8Bnhn8YWPy/l8=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-vr18
  port: 20705
  remote: 151.250.94.244:709
  wg_pubkey: O3fc+s3ZxJ0G2hYPV4PVMFaV5VWJtcvfNnmgrHAfSVc=
  peer_v4: 172.23.203.193
  peer_v6: null

- name: dn42-elrond
  port: 20620
  remote: null
  wg_pubkey: ElrOV7yaC9rCvMQfynsYpwM7yugWN0G9e0ToYMRk8i4=
  peer_v4: null
  peer_v6: fe80::620:1

- name: dn42-astutus
  port: 21014
  remote: zrh01.dn42.astutus.org:51080
  wg_pubkey: c2bRvwMy1EqsT036Qdfhpq/5bw+TjahqIYIaqHJ98nY=
  peer_v4: 172.23.114.157
  peer_v6: fe80::1014

- name: dn42-metakiwi
  port: 23564
  remote: 4.de01.dn42.metakiwi.net:21080
  wg_pubkey: y45KBG+WDESoahZiLy8jaPZgdR98B/zO62Td1dvGljA=
  peer_v4: null
  peer_v6: fe80::37:ddee

- name: dn42-chmod
  port: 22665
  remote: null
  wg_pubkey: bZVc5oXFwY0yjXAGeA7qlpt77kHkeqF27PwMwrwxOUw=
  peer_v4: null
  peer_v6: fe80::2665:129

- name: dn42-cdubs
  port: 20566
  remote: dn15.de.surgebytes.com:31080
  wg_pubkey: 6aVOMEiouO9y4FaD5eMZL2SdM7jhhuKtmRmwypy7GCo=
  peer_v4: null
  peer_v6: fe80::566

- name: dn42-rivensbane
  port: 21815
  remote: ch0.rivensbane.com:21080
  wg_pubkey: 59+xbn5n90x+bD7PxT5eozxR1CV02TrR9XhdlMn/4jg=
  peer_v4: null
  peer_v6: fe80::1815

- name: dn42-m4rc3l
  port: 21476
  remote: null
  wg_pubkey: bMTerYqi0BA5WnjgTugcXAeFIcdVqQVkstxukk5qIAA=
  peer_v4: null
  peer_v6: fe80::4c3

- name: dn42-bandura
  port: 22923
  remote: p2p-node.de:51080
  wg_pubkey: 4gf9k6UUBO55geG7377qiMt/zHVuy77X60n/vNQMtj4=
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63643062666635376434336637653735636636353531666463633765316339663930373063633731
    6337393439346238656438633764636637643234623063360a306164303233313964356337346233
    30663934333934313361353838396431656538303162346565396530383236343232646363313064
    3738326161303733610a613864343731396134636365386138393662333662613835646531613136
    30613238623863313663363538313764653061666662316137353362396230363830616436643635
    3763623966653466396462616663306233613763356534666264
  peer_v4: null
  peer_v6: fe80::2923
