wg_peers:
- name: dn42las-yura
  port: 22464
  remote: "las.dneo.moeternet.com:21080"
  wg_pubkey: "viR4CoaJTBHROo/Bgbb27hQ2ttr8AbByGY/yOz3D3GY="
  peer_v4: null
  peer_v6: "fe80::2464"

- name: dn42las-eastbnd
  port: 52633
  remote: "las.eastbnd.com:21080"
  wg_pubkey: "XQpDtLZ0/OOQgIV829vPs1SYvxQk5TlUmrTAgI5S7xg="
  peer_v4: "172.23.250.42"
  peer_v6: "fe80::2633"

- name: dn42las-miaoton
  port: 52688
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65353164386130616635343036353964333039616562643134323033386531303863366162653430
    6162366561623639366638343332633834663831303664300a346331663463336634623239646534
    37316630396236313463376665653262663439396238363261343432346438353938373039356266
    3161636463343238610a643039313766656431363834356533316135326334353234356237373662
    37646332636334643139663361633766363861636138373139373135343830343863
  wg_pubkey: "vfrrbtKAO5438daHrTD0SSS8V6yk78S/XW7DeFrYLXA="
  peer_v4: "172.23.6.6"
  peer_v6: "fe80::2688/64"

- name: dn42las-hinata
  port: 53724
  remote: "las01.us.42.katohinata.eu.org:21080"
  wg_pubkey: "W8IoIklrTsWKDJEJ35kh1aHPO9CIyyfNBF/MptzX4jw="
  peer_v4: "172.23.215.228"
  peer_v6: "fe80::3724"

- name: dn42las-lapisbl
  port: 22032
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38376164383134633730336436306438323533363433643836633366326636326366363462333738
    3932363932663930326633313131386266623964336630370a313937343439386131303234346263
    33633137613632633832373061383733366462623165346333623832333430323333383665376563
    6239613731393536340a376135636236323864636663323161323633393066623165623832383765
    65396638326161333661316363373864323532336639646264663534393561653663
  wg_pubkey: "zlIHyhapes/IwZdCZNC5nFvYjx0z1sctLYIB8HITRiI="
  peer_v4: "172.22.180.65"
  peer_v6: "fe80::2032"

- name: dn42-cola
  peer_v4: 172.22.96.65
  peer_v6: fe80::3391
  port: 23391
  remote: las.kz.al:22152
  wg_pubkey: uCrDwDvgzvirzq++JCpcMsqW6sfFBNsmEh+IWBXjHxQ=

- name: dn42-liki4
  peer_v4: null
  peer_v6: fe80::927
  port: 20927
  remote: lv1.dn42.liki.link:42429
  wg_pubkey: Ek17cwq33CvzET+L5AJRhjky62RYYfC/YviQl2V3eV0=

- name: dn42-ciplc
  peer_v4: 172.23.33.161
  peer_v6: fe80::943e
  port: 23021
  remote: us1.dn42.ciplc.network:21080
  wg_pubkey: KZXWUzmGStNRrO2vg1TbtwQKmp4gPdhOVIW4RegLVGI=

- name: dn42-iedon
  peer_v4: 172.23.91.114
  peer_v6: fe80::2189:ef
  port: 22189
  remote: us-lax.dn42.kuu.moe:58920
  wg_pubkey: DIw4TKAQelurK10Sh1qE6IiDKTqL1yciI5ItwBgcHFA=

- name: dn42-bbpgqm
  peer_v4: 172.20.56.5
  peer_v6: fe80::549:8401:0:1
  port: 20549
  remote: las.dn42.bb-pgqm.com:21080
  wg_pubkey: SRokXOA/KtaiYlwQwpEiz6liGYzJY7CtMh9YIq3P3F0=

- name: dn42-bsdrocker
  peer_v4: null
  peer_v6: fd2e:5e5e:8a3d::1022:1080
  port: 21022
  remote: null
  wg_pubkey: rRAQjGVQGBV5YqzTkZV+exM36dcBLiDF0PSEhJWRrhE=

- name: dn42-imlonghao
  port: 21888
  remote: us2.dn42.ni.sb:21080
  wg_pubkey: lAs/L2XLEZALnTOJ6ZhHaKgYY+rzqRgPnmlC4v/SfQw=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888

- name: dn42-prevarinit
  port: 22475
  remote: lvg.us.prevarinite.net:21080
  wg_pubkey: KCcJKb3+/1sjrP6B5gNBS1CpsC/ur3LHGs11feJc1lQ=
  peer_v4: null
  peer_v6: fe80::7072:6576:2

- name: dn42-lare
  port: 23035
  remote: usw1.dn42.lare.cc:21080
  wg_pubkey: Qd2XCotubH4QrQIdTZjYG4tFs57DqN7jawO9vGz+XWM=
  peer_v4: null
  peer_v6: fe80::3035:132

- name: dn42-potat0
  peer_v4: null
  peer_v6: fe80::1816
  port: 21816
  remote: us1.dn42.potat0.cc:21080
  wg_pubkey: LUwqKS6QrCPv510Pwt1eAIiHACYDsbMjrkrbGTJfviU=

- name: dn42-akihi
  port: 20398
  remote: lax.dn42.akihi.me:21080
  wg_pubkey: oAPy0U2qVuSR8PyPLmVLEgWLBKrOq4kcLNLAOVZL10M=
  peer_v4: null
  peer_v6: fe80::426f
