wg_peers:
- name: dn42-kioubit
  port: 53914
  remote: "us3.g-load.eu:21080"
  wg_pubkey: "sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8="
  peer_v4: "172.20.53.103"
  peer_v6: "fe80::ade0"
  local_v6: "fe80::ade1"

- name: dn42-zhaofeng
  port: 51926
  remote: "[2a06:e881:5502::1]:21080"
  wg_pubkey: "7/7eZZGr8S5qR+bkKaQdQQBSopjcx2xLpOM7Edw4UF4="
  peer_v4: "172.20.16.3"
  peer_v6: "fe80::1926:1"

- name: dn42-nicholascw
  port: 51288
  remote: "lax2.sc00.org:21080"
  wg_pubkey: "PGTK1pzAYtSGoaPYfpEBCwm3S3gYAra3WkSMtshFfW8="
  peer_v4: "172.20.233.131"
  peer_v6: "fe80::1288/64"

- name: dn42-ykis
  remove: true

- name: dn42-mayli
  remove: true

- name: dn42las-yura
  port: 22464
  remote: "las.dneo.moeternet.com:21080"
  wg_pubkey: "viR4CoaJTBHROo/Bgbb27hQ2ttr8AbByGY/yOz3D3GY="
  peer_v4: null
  peer_v6: "fe80::2464"
  local_v4: 172.20.229.126
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42las-eastbnd
  remove: true

- name: dn42las-miaoton
  port: 52688
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65353164386130616635343036353964333039616562643134323033386531303863366162653430
    6162366561623639366638343332633834663831303664300a346331663463336634623239646534
    37316630396236313463376665653262663439396238363261343432346438353938373039356266
    3161636463343238610a643039313766656431363834356533316135326334353234356237373662
    37646332636334643139663361633766363861636138373139373135343830343863
  wg_pubkey: "vfrrbtKAO5438daHrTD0SSS8V6yk78S/XW7DeFrYLXA="
  peer_v4: "172.23.6.6"
  peer_v6: "fe80::2688/64"
  local_v4: 172.20.229.126
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42las-hinata
  remove: true

- name: dn42las-lapisbl
  remove: true

- name: dn42-liki4
  remove: true

- name: dn42-iedon
  peer_v4: 172.23.91.114
  peer_v6: fe80::2189:ef
  port: 22189
  remote: us-lax.dn42.kuu.moe:58920
  wg_pubkey: DIw4TKAQelurK10Sh1qE6IiDKTqL1yciI5ItwBgcHFA=
  local_v4: 172.20.229.126
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42-bsdrocker
  remove: true

- name: dn42-imlonghao
  port: 21888
  remote: us2.dn42.ni.sb:21080
  wg_pubkey: lAs/L2XLEZALnTOJ6ZhHaKgYY+rzqRgPnmlC4v/SfQw=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888
  local_v4: 172.20.229.126
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42-prevarinit
  remove: true

- name: dn42-potat0
  peer_v4: null
  peer_v6: fe80::1816
  port: 21816
  remote: us1.dn42.potat0.cc:21080
  wg_pubkey: LUwqKS6QrCPv510Pwt1eAIiHACYDsbMjrkrbGTJfviU=
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42-akihi
  port: 20398
  remote: lax.dn42.akihi.me:21080
  wg_pubkey: oAPy0U2qVuSR8PyPLmVLEgWLBKrOq4kcLNLAOVZL10M=
  peer_v4: null
  peer_v6: fe80::426f
  local_v6: fe80::1080:126
  wg_privkey: /etc/wireguard/privatekey_las

- name: dn42-dgy
  remove: true

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030:18
  port: 22717
  remote: usw.vm.whojk.com:23005
  wg_pubkey: L4+efr10ZM0J80nDeO5mHw25nq9LC5UBrYtP8T1I9n4=

- name: dn42-lantian
  peer_v4: 172.22.76.185
  peer_v6: fe80::2547
  port: 22547
  remote: hostdare.lantian.pub:21080
  wg_pubkey: zyATu8FW392WFFNAz7ZH6+4TUutEYEooPPirwcoIiXo=

- name: dn42-131
  peer_v4: 172.21.109.34
  peer_v6: fe80::1131
  port: 21131
  remote: phoenix.us.dn42.yuzu.im:20247
  wg_pubkey: abDdEXgpaUNfEVPYLv1GTA+1TjkRbk5MNUi0fczYflw=

- name: dn42-naivetomca
  port: 23309
  remote: "lax.tsinghuamakerxian.cn:21080"
  wg_pubkey: "C9QViSndf1zga5nOoSoXXMLUWBJvEFiJDWSFCbU1Ynw="
  peer_v4: "172.23.163.161"
  peer_v6: "fe80::3309"

- name: dn42-sunnet
  port: 53088
  remote: "lax1-us.dn42.6700.cc:21080"
  wg_pubkey: "QSAeFPotqFpF6fFe3CMrMjrpS5AL54AxWY2w1+Ot2Bo="
  peer_v4: "172.21.100.193"
  peer_v6: "fe80::3088:193/64"

- name: dn42-lare
  port: 23035
  remote: usw2.dn42.lare.cc:21080
  wg_pubkey: oWMjftHTU+ll9PG26adiQaipQ8HC6kO4puXGakw38j8=
  peer_v4: null
  peer_v6: fe80::3035:139

- name: dn42-colby
  port: 22558
  remote: us-lax1.dn42.derix.au:21080
  wg_pubkey: s3IVH2xJ3oRekd4x4Bc2H2pb0YZD11FT7Unxttc7GCU=
  peer_v4: null
  peer_v6: fe80::2558:7

- name: dn42-tech9
  port: 21588
  remote: us-phx03.dn42.tech9.io:55968
  wg_pubkey: bRkI8aGjwwgm1I6WeqsfL6jrxu72ifs3xSaTLCY22mw=
  peer_v4: 172.23.220.178
  peer_v6: fe80::1588
  local_v6: fe80::100

- name: dn42-moraxyc
  port: 23011
  remote: us-lax3.dn42.moraxyc.com:21080
  wg_pubkey: eB+NSqo26tqITGZhMdVkJ0aZ+ZANELjzstdF1MfzRRw=
  peer_v4: null
  peer_v6: fe80::3011:3

- name: dn42-burble
  peer_v4: null
  peer_v6: fe80::42:2601:2a:1
  port: 22601
  remote: dn42-us-lax1.burble.com:21080
  wg_pubkey: MDjt4DyKGFumReT9pBJL6mPbDfQDfhPFyzHGDeoQVBQ=

- name: dn42-jasonxu
  remove: true

- name: dn42-rubick
  port: 23451
  remote: v4-la.zub.pub:21080
  wg_pubkey: 3RiYYcOW4AJeO5RRMezDHjDCOGKjUz/1lmdpVHcdSkc=
  peer_v4: null
  peer_v6: fe80::3451

- name: dn42-moechs
  port: 21522
  remote: null
  wg_pubkey: JtesX7JLjlYmZWbeMvK2Hx0Vpo5Fhr9VILlTcuonlWQ=
  peer_v4: null
  peer_v6: fe80::1522

- name: dn42-sidereal
  port: 22016
  remote: phx1.dn42.sidereal.ca:21080
  wg_pubkey: 3hy0FIf64sxSVLY6/CwhtMfCmQEkG5hsyKxM/Dttvz0=
  peer_v4: null
  peer_v6: fe80::2016
