wg_peers:
- name: dn42-napster
  port: 51050
  remote: mcr1-uk.dn42.napshome.net:51080
  wg_pubkey: "eNgNR4SXD7aBnE7POW/asfsw2BiVmjEz684zC8WAITo="
  peer_v4: "172.22.169.140"
  peer_v6: "fda9:26a9:1c47:2d42:42:42:1080:1050"
  bgp:
    asn: 4242421050
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-jrb0001
  port: 50119
  remote: "45.63.101.40:21080"
  wg_pubkey: "79RlgA68KnWS7i9TarFuNBIsT4WzKGSHyJmffbOzbCg="
  peer_v4: "172.20.1.3"
  peer_v6: "fe80::119"
  bgp:
    asn: 4242420119
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-jerry
  port: 53618
  remote: "nl.neo.jerryxiao.cc:50090"
  wg_pubkey: "zE9C015v2H0duvNBdXm2ToWqimoIlBqtZtFTqgLQXgs="
  peer_v4: null
  peer_v6: "fe80::3618/64"
  bgp:
    asn: 4242423618
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-andi
  port: 53991
  remote: "iota.h4ck.space:42029"
  wg_pubkey: "s6OL5S5GvUykOs1XVAWL2i6Mflk6niZ4BZhrHmdB5Gw="
  peer_v4: null
  peer_v6: "fe80::1"
  bgp:
    asn: 4242423991
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

# Automatically removed on 2025-02-16 (down for >= 40 days)
- name: dn42-servermade
  remove: true

# Automatically removed on 2025-02-16 (down for >= 40 days)
- name: dn42-camelus
  remove: true

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: uk1.dn42.atolm.net:21080
  wg_pubkey: W5tOp5Iw/uJppISGF9KSQL5/q9ykW0PUSAKDe4YPXHQ=
  bgp:
    asn: 4242420585
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-rhysperry
  peer_v4: 172.22.76.1
  peer_v6: null
  port: 23665
  remote: rhysperry.com:55505
  wg_pubkey: I1WlxMXrSoN2g3WVJNYNG+4MsYhJwNA6UYgt5pHOGGY=
  bgp:
    asn: 4242423665
    extended_next_hop: false
    ipv4: true
    ipv6: false
    mp_bgp: false

- name: dn42-htw
  peer_v4: 172.21.78.33
  peer_v6: fe80::1440:1080
  port: 21440
  remote: sco1.dn42.canidae.systems:26005
  wg_pubkey: YoB/Tge5Teb1ycnbi/vjmcsyD8My4waVkNhupn7JnDk=
  bgp:
    asn: 4242421440
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-kioubit
  port: 23914
  remote: uk1.g-load.eu:21080
  wg_pubkey: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
  peer_v4: 172.20.53.104
  peer_v6: fe80::ade0
  bgp:
    asn: 4242423914
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sfsarfe
  port: 21780
  remote: null
  wg_pubkey: 73cKStIwW3HrDepdmix6hbLPBNb2/XM92AVBv78f+FQ=
  peer_v4: 172.22.132.80
  peer_v6: fe80::102
  bgp:
    asn: 4242421780
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cellardoor
  port: 21774
  remote: null
  wg_pubkey: obTX3Gz9eeHsBmg1u0XwXOSwLBA70bN8Z1ww3djy+jk=
  peer_v4: null
  peer_v6: fdc0:b62e:4a7d:cafe:cafe:cafe:cafe:2
  local_v6: fdc0:b62e:4a7d:cafe:cafe:cafe:cafe:1
  bgp:
    asn: 4242421774
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sidereal
  port: 22016
  remote: lon1.dn42.sidereal.ca:21080
  wg_pubkey: IsuXPz73qeUi+HfGlkkJnPxSqQKd5drx2dkjuHuuL1k=
  peer_v4: null
  peer_v6: fe80::2016
  bgp:
    asn: 4242422016
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-tildegreen
  port: 20953
  remote: dn42peer.tilde.green:21080
  wg_pubkey: VnkrpG4H2XwmpQvb+Wh4RVAa7r94juW4Eu4133qQnFQ=
  peer_v4: null
  peer_v6: fe80:0000:0000:0000:215d:4229:2c80:9b69
  bgp:
    asn: 4242420953
    extended_next_hop: false
    ipv4: false
    ipv6: true
    mp_bgp: false

- name: dn42-baragoon
  port: 21732
  remote: chr-lo01.as215887.net:21080
  wg_pubkey: qe7bmJgd2ftxE9OYPL6Q4gZK6lvSqKPn5BynDXHsvzM=
  peer_v4: 172.23.32.128
  peer_v6: fe80::1732
  bgp:
    asn: 4242421732
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-flisk
  port: 20390
  remote: "2a01:e0a:dc0:1d1::42:42002"
  wg_pubkey: BE4QCk0fhX1rbpjaNZz1hnBoyUAWUuxDAfo8f9pfTRo=
  peer_v4: 172.21.107.33
  peer_v6: fe80::390
  bgp:
    asn: 4242420390
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-fmepnet
  port: 23703
  remote: uk-lon0.fmepnet.org:51828
  wg_pubkey: Z0o4rgqUTA5OT6BjhJBt4ClTb4rz0GsC5jvAfn+s53A=
  peer_v4: 172.20.159.237
  peer_v6: fe80::3703:237
  bgp:
    asn: 4242423703
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-lefay
  port: 21495
  remote: 2001:ba8:4015:1::1:11214
  wg_pubkey: bBuSGihjkjkay6pt1bFacZx2OBmxt3KBQdYLXnDtJEY=
  peer_v4: null
  peer_v6: fe80::1
  bgp:
    asn: 4242421495
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-9pfs
  port: 22002
  remote: null
  wg_pubkey: sDvoqtg1OcmNCXuuES+wKHyrSqANDElI2iLQQnZByzo=
  peer_v4: null
  peer_v6: fe80::2002:3
  bgp:
    asn: 4242422002
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-joenet
  port: 20157
  remote: ire01.ke8jwh.com:31080
  wg_pubkey: HwnW9T5AgETDfPi4EqExeBzi0j6EeKEV/M5Nb0iUQEU=
  peer_v4: null
  peer_v6: fe80::157:237
  bgp:
    asn: 4242420157
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-sdubs
  port: 20202
  remote: dn07.lon.uk.sdubs.vip:21080
  wg_pubkey: NNzS8SVIMmPHaYIsdy9BkE0oG+2y+71bWLDbSp48cw0=
  peer_v4: null
  peer_v6: fe80::202:7
  bgp:
    asn: 4242420202
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sm1755
  port: 21755
  remote: core1.router.net.ukse1.sidingsmedia.com:21080
  wg_pubkey: 8rdWhwxdaSY8GE9jHN7zh5PodvnoeVzQQLtN0IHCY1o=
  peer_v4: null
  peer_v6: fe80::1755:1080
  bgp:
    asn: 4242421755
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-optistream
  port: 22096
  remote: null
  wg_pubkey: Aao+tCL6FMS8qwy1HKfflCzJZpwz5IDkE3WjD79h7mQ=
  peer_v4: null
  peer_v6: fe80::2096
  bgp:
    asn: 4242422096
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
