wg_peers:
- name: dn42-napster
  port: 51050
  remote: mcr1-uk.dn42.napshome.net:51080
  wg_pubkey: "eNgNR4SXD7aBnE7POW/asfsw2BiVmjEz684zC8WAITo="
  peer_v4: "172.22.169.140"
  peer_v6: "fda9:26a9:1c47:2d42:42:42:1080:1050"

- name: dn42-jrb0001
  port: 50119
  remote: "45.63.101.40:21080"
  wg_pubkey: "79RlgA68KnWS7i9TarFuNBIsT4WzKGSHyJmffbOzbCg="
  peer_v4: "172.20.1.3"
  peer_v6: "fe80::119"

- name: dn42-raito
  port: 51457
  remote: "[2a01:e0a:5f9:9681::2]:21080"
  wg_pubkey: "5TxBJx9R22Du8cuoE4y59SdERwmgfmDF+9lmnIE8XD8="
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63623763346461306535343534323664306361343234363937346362356337393230316131326164
    6162346231316265653531316132613831326332653139610a393835383966343636363935393539
    63373765373166383936373331623233363538383931373463303761663130633033316363303361
    6262363136353437380a656165643835313730363136383466356331323665353661316537646335
    63656666383139653565376539616663643766613630343634386235663733393661316566356332
    3838613836383936323462386563643563373539353837626464
  peer_v4: null
  peer_v6: "fd4d:ce73:68f9:9a62::3"

- name: "dn42-munsternet"
  port: 52237
  remote: "uk-lon01.dn42.munsternet.eu:21080"
  wg_pubkey: "rNs2OSnzI7flkzOgCv7zC+AqehEo55jhd4GvFl8QdGk="
  peer_v4: null
  peer_v6: "fe80::42:2237/128"

- name: dn42-jerry
  port: 53618
  remote: "nl.neo.jerryxiao.cc:50090"
  wg_pubkey: "zE9C015v2H0duvNBdXm2ToWqimoIlBqtZtFTqgLQXgs="
  peer_v4: null
  peer_v6: "fe80::3618/64"

- name: dn42-andi
  port: 53991
  remote: "iota.h4ck.space:42029"
  wg_pubkey: "s6OL5S5GvUykOs1XVAWL2i6Mflk6niZ4BZhrHmdB5Gw="
  peer_v4: null
  peer_v6: "fe80::1"

- name: dn42-servermade
  port: 53770
  remote: "rbx1.dn42.servermade.com:51080"
  wg_pubkey: "0ndXPAg17zmVx5CfxMblRfdcDjHRDB6OKBkYvvtq1g0="
  peer_v4: "172.22.118.129"
  peer_v6: "fe80::3770/64"

- name: dn42-camelus
  port: 21592
  remote: "uk01.dn42.trampel.org:41080"
  wg_pubkey: "oUFScw06Qe6nyDWwbywdecgnt1QQNWe1DFAUb3QCqgU="
  peer_v4: "172.21.99.188"
  peer_v6: "fe80::1592"

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: uk1.dn42.atolm.net:21080
  wg_pubkey: W5tOp5Iw/uJppISGF9KSQL5/q9ykW0PUSAKDe4YPXHQ=

- name: dn42-rhysperry
  peer_v4: 172.22.76.1
  peer_v6: null
  port: 23665
  remote: rhysperry.com:55505
  wg_pubkey: I1WlxMXrSoN2g3WVJNYNG+4MsYhJwNA6UYgt5pHOGGY=

- name: dn42-htw
  peer_v4: 172.21.78.33
  peer_v6: fe80::1440:1080
  port: 21440
  remote: sco1.dn42.canidae.systems:26005
  wg_pubkey: YoB/Tge5Teb1ycnbi/vjmcsyD8My4waVkNhupn7JnDk=

- name: dn42-bandura
  peer_v4: 172.22.149.225
  peer_v6: fe80::2923
  port: 22923
  remote: p2p-node.de:51080
  wg_pubkey: 4gf9k6UUBO55geG7377qiMt/zHVuy77X60n/vNQMtj4=

- name: dn42-kioubit
  port: 23914
  remote: uk1.g-load.eu:21080
  wg_pubkey: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
  peer_v4: 172.20.53.104
  peer_v6: fe80::ade0

- name: dn42-sfsarfe
  port: 21780
  remote: null
  wg_pubkey: 73cKStIwW3HrDepdmix6hbLPBNb2/XM92AVBv78f+FQ=
  peer_v4: 172.22.132.80
  peer_v6: fe80::102

- name: dn42-cellardoor
  port: 21774
  remote: null
  wg_pubkey: obTX3Gz9eeHsBmg1u0XwXOSwLBA70bN8Z1ww3djy+jk=
  peer_v4: null
  peer_v6: fdc0:b62e:4a7d:cafe:cafe:cafe:cafe:2
  local_v6: fdc0:b62e:4a7d:cafe:cafe:cafe:cafe:1
