wg_peers:
- name: dn42-routedbits
  port: 20207
  remote: router.mum1.routedbits.com:51080
  wg_pubkey: RgwTfRAivLpvkeenTQMwNyLU55W5EZfYnXGjWTAY5yw=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-prefixlabs
  port: 21240
  remote: in-01.prefixlabs.net:21080
  wg_pubkey: IS0LGxUIUUfeptK5ZK5Fwu3RZTnM/n90Ztsx6I4NSDo=
  peer_v4: 172.20.209.15
  peer_v6: fe80::1240:6
  bgp:
    asn: 4242421240
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-cdubs
  port: 20566
  remote: dn20.in.surgebytes.com:31080
  wg_pubkey: ZkGeLAmwOwEKFRDTsnWnfnZlWQ1SgW9jUUx6O8+tCnA=
  peer_v4: null
  peer_v6: fe80::566:20
  bgp:
    asn: 4242420566
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-segfault
  port: 23443
  remote: router.uchinoie.site:51080
  wg_pubkey: PL+bwsJypqEs/oSUkEQKL2EkM4xagyJXSZLqNVrMFTI=
  peer_v4: null
  peer_v6: fe80::3443:1080
  bgp:
    asn: 4242423443
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-leslie
  port: 23264
  remote: 140.238.228.228:51823
  wg_pubkey: 3BbR49ma6Vk2xtYJ16TUhy0R/9V05N70BfHuZgUVfGE=
  peer_v4: 172.20.48.2
  peer_v6: fd64:8964:8964::2
  bgp:
    asn: 4242423264
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false
