wg_peers:
- name: cl-roam
  local_v4: 172.22.108.57/29
  local_v6_multi:
  - fd86:bad:11b7:1:2::1/124
  - 2606:6680:19:140::9/125
  # A dummy link local v6 is needed for BIRD to pick this up as an OSPF stub interface for IPv6
  - "{{ link_local_ip6 }}"
  port: 21080
  multi:
    # sixel
  - wg_pubkey: "aJUsDF7fducvds8FjS4KsqzDrxBNO2g8sY2caAVOFFc="
    wg_allowedips: "172.22.108.58/32,fd86:bad:11b7:1:2::2/128,2606:6680:19:140::a/128"
    # silverthing
  - wg_pubkey: "jSb/GMN0S46JzENLIZeeC/jyfKZXg5wAYPhnecohegE="
    wg_allowedips: "172.22.108.59/32,fd86:bad:11b7:1:2::3/128,2606:6680:19:140::b/128"
  peer_v6: null

- name: cl-gamenet
  local_v4: 172.22.108.89/29
  port: 21081
  multi:
  - wg_pubkey: "9Eq6x9xANmDa6rwvUeOX/VbJI7FexMqByBkWIrHGyA0="
    wg_allowedips: "172.22.108.90/32"
  - wg_pubkey: "fKs/XbykQQeMHWM64g8hH2c1vPc+w3Qqorg4YZHzyiw="
    wg_allowedips: "172.22.108.91/32"
  - wg_pubkey: "x223mAF6rM9Ea3U/0TSHQEMfWJ+jpLxyO9wxAUE3qh4="
    wg_allowedips: "172.22.108.92/32"
  wg_privkey: /etc/wireguard/privatekey_gamenetwest

- name: igp-yvrlab
  port: 19999
  wg_pubkey: "2Xn6+lC+WLM5cxeKG3xPwuOcUKw2fSvve9oGMXgoeRw="
  peer_v4: null
  local_v4: 172.22.108.76/31
  peer_v6: fe80::d979:fafa:50be:58b3

- name: dn42-sirmysteri
  port: 51475
  remote: "dn42-us-sfo1.sirmysterion.com:51475"
  wg_pubkey: "S1Pm3Oqdn6flQ15WoG5n+FQhyGPPS5Xdh98VQwephjA="
  peer_v4: "172.20.20.98/32"
  peer_v6: "fe80::b562"

- name: dn42sea-ncw
  port: 51288
  remote: "sea1.sc00.org:21080"
  wg_pubkey: "AMmUVNOn6ZtL0+vn1tfO4c7M1Fby19lSVZpJJhML6VI="
  peer_v4: "172.20.233.153"
  peer_v6: "fe80::1288/64"

- name: dn42-yukino
  port: 21255
  remote: dn42-us-sea1.acgcl.net:31080
  wg_pubkey: 5S6ZAEZtXa5uockijxilgwhsHzeeTS/W0ws5ops8BFY=
  peer_v4: null
  peer_v6: fe80::1070

- name: dn42-bandura
  port: 22923
  remote: stricker.mk16.de:51080
  wg_pubkey: zxVkfI38Yb9SBmccT7vabu8P8C6jI3faZKfSAH+1onU=
  peer_v4: null
  peer_v6: fe80::2923
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64663135616235353034343439316636326333613936653337343166386434643034326134663532
    3336623236353965356164353434306331653930346162330a663535636131313338376239356261
    66373432353762376436303266336430343332363037393432396366653136393039643035356232
    6334653164376162360a336561373932626334373563626132313061646261646332626366646566
    38623737663136333734633465646631653462306661623037666432646364613930386563663961
    3964303036316237653131383161303538386634333439633362

- name: dn42-piggy
  port: 22705
  remote: sea1.node.piggy.moe:21080
  wg_pubkey: DyiUEXYuE6TNhfqj4c3MZdUOrjAxs6BbRhjImF251WA=
  peer_v4: null
  peer_v6: fe80::4242:2705
  local_v6: fe80::1080:5
  wg_privkey: /etc/wireguard/privatekey_yvrpeer

- name: dn42-sunnet
  port: 23088
  remote: sea1-us.dn42.6700.cc:21080
  wg_pubkey: v5hkjo2W88ddB1V5nMMJvr6CVoEkQ0AtZp+K2iFMSjs=
  peer_v4: null
  peer_v6: fe80::3088:215
  local_v6: fe80::abcd

- name: dn42-kiyomi
  port: 21350
  remote: sea.jvav.tech:21080
  wg_pubkey: k6RlAqY+CXvC7Kogys1U9solqYhFmXt+Ykzdmiat0W8=
  peer_v4: 172.20.39.81
  peer_v6: fe80::1350

- name: dn42-routedbits
  port: 20207
  remote: router.sea1.routedbits.com:51080
  wg_pubkey: /aY73VNAGQ7W+GersZUSO6PqHJV8nWKb12Op9EQzY3k=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-colby
  port: 22558
  remote: us-pdx1.dn42.derix.au:21080
  wg_pubkey: pEgl/q/fxrcdnqEur25ZKrIkOvoISDVBrU80R86jY1Q=
  peer_v4: null
  peer_v6: fe80::2558:2
