wg_peers:
- name: cl-roam
  local_v4: 172.22.108.100/31
  local_v6_multi:
  - fd86:bad:11b7:83::1/64
  # A dummy link local v6 is needed for BIRD to pick this up as an OSPF stub interface for IPv6
  - "{{ link_local_ip6 }}"
  port: 19998
  wg_pubkey: aJUsDF7fducvds8FjS4KsqzDrxBNO2g8sY2caAVOFFc=
  peer_v6: null
