wg_peers:
- name: dn42-hackclub
  port: 20392
  remote: hackclub.app:21080
  wg_pubkey: BOI9J1hyFwlbjatNi9NUUMVnRXSOwBpb0f+Cgwl4p28=
  peer_v4: null
  peer_v6: fe80::392
  bgp:
    asn: 4242420392
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cdubs
  port: 20566
  remote: dn13.se.surgebytes.com:31080
  wg_pubkey: r4RXdmZHB2gPNY9zgggFZM7KVsFcoHbz4zHw1K43IVc=
  peer_v4: null
  peer_v6: fe80::566:13
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-m724
  port: 20129
  remote: ipv4.se1.420129.xyz:21080
  wg_pubkey: tS6j+/aroaMYT/mbzv4xDGI7bc6/LAgwc/KKrw/LIVI=
  peer_v4: null
  peer_v6: fe80::129:5
  bgp:
    asn: 4242420129
    ipv4: false
    ipv6: true
    mp_bgp: false
    extended_next_hop: false

- name: dn42-myxoz
  port: 20166
  remote: swehadgw-dn42.myxoz.net:21080
  wg_pubkey: FVOlERXyZs9IALktRx99ROBFCwPb2oqA+6qWx+ZTiWI=
  peer_v4: null
  peer_v6: fe80::2166
  bgp:
    asn: 4242420166
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-alemal
  port: 21525
  remote: fi1.alemal.se:51080
  wg_pubkey: Z3cYtfkA/0yE8qAC1RMeBXKFYGkDbWMiXuohiTOaehc=
  peer_v4: null
  peer_v6: fe80::1525
  bgp:
    asn: 4242421525
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-zyner
  port: 20900
  remote: dn42.selud02.zyner.net:21080
  wg_pubkey: Odxqq2L5HH26owU2Qu2zZsZbrYj/TyfpUhUxOaOyjyY=
  peer_v4: null
  peer_v6: fe80::0900
  bgp:
    asn: 4242420900
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-sa0wii
  port: 20019
  remote: sto.dn42.sa0wii.se:20019
  wg_pubkey: 4iX21JQa0Z6pYjoSdMrNhRx2gwyF2xO3iMS7qV9zzVc=
  peer_v4: null
  peer_v6: fe80::19
  bgp:
    asn: 4242420019
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
