wg_peers:
- name: dn42-hackclub
  port: 20392
  remote: hackclub.app:21080
  wg_pubkey: BOI9J1hyFwlbjatNi9NUUMVnRXSOwBpb0f+Cgwl4p28=
  peer_v4: null
  peer_v6: fe80::392
  bgp:
    asn: 4242420392
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cdubs
  port: 20566
  remote: dn13.se.surgebytes.com:31080
  wg_pubkey: r4RXdmZHB2gPNY9zgggFZM7KVsFcoHbz4zHw1K43IVc=
  peer_v4: null
  peer_v6: fe80::566:13
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-m724
  port: 20129
  remote: ipv4.se1.420129.xyz:21080
  wg_pubkey: tS6j+/aroaMYT/mbzv4xDGI7bc6/LAgwc/KKrw/LIVI=
  peer_v4: null
  peer_v6: fe80::129:5
  bgp:
    asn: 4242420129
    ipv4: false
    ipv6: true
    mp_bgp: false
    extended_next_hop: false

# Automatically removed on 2025-06-14 (down for >= 40 days)
- name: dn42-heartbleed
  remove: true

- name: dn42-myxoz
  port: 20166
  remote: swehadgw-dn42.myxoz.net:21080
  wg_pubkey: FVOlERXyZs9IALktRx99ROBFCwPb2oqA+6qWx+ZTiWI=
  peer_v4: null
  peer_v6: fe80::2166
  bgp:
    asn: 4242420166
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-alemal
  port: 21525
  remote: de1.alemal.se:51080
  wg_pubkey: qHb6OYN81sMO5n23xSeFyaW12cOoVbnPQcZNFeGXp38==
  peer_v4: null
  peer_v6: fe80::1525
  local_v6: fe80::1080:121
  bgp:
    asn: 4242421525
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
