wg_peers:
- name: dn42-narnia
  port: 52037
  remote: "syd2.dn42.narnia.network:42011"
  wg_pubkey: "0T0LUDBHnWAAg5Kz4OBF0r0+r+9WHtaUsvywKZSci2I="
  peer_v4: null
  peer_v6: "fd23:0:0:ffff::2037"
  bgp:
    asn: 4242422037
    extended_next_hop: false
    ipv4: false
    ipv6: true
    mp_bgp: false

- name: dn42-kskb
  peer_v4: 10.127.111.81
  peer_v6: fe80::aa:1111:51
  port: 21111
  remote: null
  wg_pubkey: Q7KOnB3xhaTNpszgozEXdq1cxBpYIX1JUMNV5J5JMwo=
  bgp:
    asn: 4201271111
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-186526
  peer_v4: 172.23.2.94
  peer_v6: fe80::ade1
  port: 23764
  remote: au-sydney-02.edge.186526.xyz:21080
  wg_pubkey: G7Omvtm569Rd4PtffJp2p1bM/eve87mFM6Hlu29vRBc=
  bgp:
    asn: 4242423764
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: au-east1.nodes.huajinet.org:21080
  wg_pubkey: LeNGkX12n1Dcq8eNE1HhvpnFxrPlzgWlNncFlHdi5DY=
  bgp:
    asn: 4242420458
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-imlonghao
  port: 21888
  remote: au1.dn42.ni.sb:21080
  wg_pubkey: Syd/jYnhMvDrvp1POVCLuAlagWjV9X/A5DCbEBpdFBc=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888
  bgp:
    asn: 4242421888
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.syd1.routedbits.com:51080
  wg_pubkey: wgCrE2lSvrfctVSngdHo6iAT/RRK7gNldJcFIFKi/Go=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-colby
  port: 22558
  remote: au-syd1.dn42.derix.au:21080
  wg_pubkey: Lhg2KWIFATOatdf/qLyTmAs0XEImX2oPzqoZKCMMlw8=
  peer_v4: null
  peer_v6: fe80::2558:1
  bgp:
    asn: 4242422558
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-rivensbane
  port: 21815
  remote: au1.rivensbane.com:21080
  wg_pubkey: R5fOFXqd3bvfCt42oe3+qaqGY7gbsYpK8wLBc1o6/Ec=
  peer_v4: null
  peer_v6: fe80::1815
  bgp:
    asn: 4242421815
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-lucaslah
  port: 23290
  remote: 119.224.65.18:21080
  wg_pubkey: XJ/JV4983nfMhns2B86nEYUyBt1FGAl0dh5THgFdwVY=
  peer_v4: null
  peer_v6: fe80::3290:1
  bgp:
    asn: 4242423290
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-peer
  port: 20343
  remote: etana.s.nullcontent.net:31080
  wg_pubkey: 3UrAkm2gcI6ZC3uVANx90bLkGN6a67SI1r8YGB56DX4=
  peer_v4: null
  peer_v6: fe80::343:3
  bgp:
    asn: 4242420343
    extended_next_hop: false
    ipv4: false
    ipv6: true
    mp_bgp: false

- name: dn42-cdubs
  port: 20566
  remote: dn22.syd.surgebytes.com:31080
  wg_pubkey: PNt5s29/1P0GsTpc5Ffk3WNp2OLD4V0zPxcjVR4U1RY=
  peer_v4: null
  peer_v6: fe80::566:22
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-prefixlabs
  port: 21240
  remote: au-01.prefixlabs.net:21080
  wg_pubkey: 0OapC67LuwIjvMkJ56lOEoPGHi+ZMA4A3qU0cjpG+Aw=
  peer_v4: 172.20.209.20
  peer_v6: fe80::1240:12
  bgp:
    asn: 4242421240
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-badaimweeb
  port: 23797
  remote: 12ee65e53ef756b115b01fe1ced14cec6dd3f024.dc.badaimweeb.me:5602
  wg_pubkey: uSfj7LEDt0VHP2jbacFkzx/JzSCExzax38BhPorj6x4=
  peer_v4: null
  peer_v6: fe80::bad0:1080
  bgp:
    asn: 4242423797
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true
