wg_peers:
- name: dn42syd-narnia
  port: 52037
  remote: "syd2.dn42.narnia.network:42011"
  wg_pubkey: "0T0LUDBHnWAAg5Kz4OBF0r0+r+9WHtaUsvywKZSci2I="
  peer_v4: null
  peer_v6: "fd23:0:0:ffff::2037"

- name: dn42-kskb
  peer_v4: 10.127.111.81
  peer_v6: fe80::aa:1111:51
  port: 21111
  remote: null
  wg_pubkey: Q7KOnB3xhaTNpszgozEXdq1cxBpYIX1JUMNV5J5JMwo=

- name: dn42-186526
  peer_v4: 172.23.2.94
  peer_v6: fe80::ade1
  port: 23764
  remote: au-sydney-02.edge.186526.xyz:21080
  wg_pubkey: G7Omvtm569Rd4PtffJp2p1bM/eve87mFM6Hlu29vRBc=

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: au-east1.nodes.huajinet.org:21080
  wg_pubkey: LeNGkX12n1Dcq8eNE1HhvpnFxrPlzgWlNncFlHdi5DY=

- name: dn42-lare
  port: 23035
  remote: null
  wg_pubkey: OhpIfAMN/YsQrl/gMPDr8OwFkVXvREpmrfjPv3U5/Fg=
  peer_v4: 172.22.125.134
  peer_v6: fe80::3035:134

- name: dn42-imlonghao
  port: 21888
  remote: au1.dn42.ni.sb:21080
  wg_pubkey: Syd/jYnhMvDrvp1POVCLuAlagWjV9X/A5DCbEBpdFBc=
  peer_v4: 172.22.68.0
  peer_v6: fe80::1888

- name: dn42-routedbits
  port: 20207
  remote: router.syd1.routedbits.com:51080
  wg_pubkey: wgCrE2lSvrfctVSngdHo6iAT/RRK7gNldJcFIFKi/Go=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-jack
  port: 22971
  remote: syd01.dn42.jackscott.xyz:51080
  wg_pubkey: 5b/QZxY2406E+it3M7k1r7jOzs7a0sogz47faHfCblc=
  peer_v4: 172.23.159.65
  peer_v6: fe80::2971:1

- name: dn42-colby
  port: 22558
  remote: au-syd1.dn42.derix.au:21080
  wg_pubkey: Lhg2KWIFATOatdf/qLyTmAs0XEImX2oPzqoZKCMMlw8=
  peer_v4: null
  peer_v6: fe80::2558:1
