wg_peers:
- name: dn42-tech9
  port: 51588
  remote: "jp-tyo01.dn42.tech9.io:52952"
  wg_pubkey: "unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM="
  peer_v4: "172.20.16.145/32"
  peer_v6: "fe80::1588/64"
  local_v6: "fe80::100"
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-yura
  port: 22464
  remote: "nrt.dneo.moeternet.com:21080"
  wg_pubkey: "tDNRiZDVxwzdYdoi+5ydgLwpVu252aP7y+NKxfAzyVY="
  peer_v4: null
  peer_v6: "fe80::2464/64"
  bgp:
    asn: 4242422464
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-jerry
  port: 53618
  remote: jpn.neo.jerryxiao.cc:50101
  wg_pubkey: "7c3/iRHLHL/DGPacgZf+JSnNBtKT4fUKaQw2xPUpAGE="
  peer_v4: null
  peer_v6: "fe80::3618/64"
  bgp:
    asn: 4242423618
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-kskb1817
  port: 21817
  remote: "4.jp.kskb.eu.org:21080"
  wg_pubkey: "jxCsSXtUSVjaP+eMWOyRsHg3JShQfBFEtyssMKWQaS8="
  peer_v4: null
  peer_v6: "fe80::42:1817:1"
  bgp:
    asn: 4242421817
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-iedon
  port: 22189
  remote: jp-tyo.dn42.kuu.moe:54764
  wg_pubkey: u2ImAJn9ewce9YHN6HaqrR3Sr4Xsy5UaaJOLJ7gkSzs=
  peer_v4: null
  peer_v6: fe80::2189:ee
  bgp:
    asn: 4242422189
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-yurui
  port: 52330
  remote: "tp01.tw.node.argonauts.xyz:51080"
  wg_pubkey: "LNpOdAZMc2RszmMB/JrvGoqLt8aE+p9JyYODKphzyyw="
  peer_v4: "172.23.32.5"
  peer_v6: "fe80::2330:5"
  bgp:
    asn: 4242422330
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-kskb
  peer_v4: 10.127.111.9
  peer_v6: fe80::aa:1111:9
  port: 21111
  remote: null
  wg_pubkey: 2CxGhL9UwlCB3ybwD1OF2Or18vCPgChS0rdh3Nc8S0c=
  bgp:
    asn: 4201271111
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030
  port: 22717
  remote: jp.vm.whojk.com:23014
  wg_pubkey: ifN+KmnL5XLHG8nDi2nN9l26snGUP/1157p8mOSPE1c=
  bgp:
    asn: 4242422717
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: jp1.dn42.atolm.net:21080
  wg_pubkey: UNSqegT4PRWe6507kvlMsqj5YKxdcvQe2zedDL0k8Ww=
  bgp:
    asn: 4242420585
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: jp1.nodes.huajinet.org:21080
  wg_pubkey: lLcWnM8vTogYe4H96zSeKmtz8MBL+g0ajnMcFDsYIk8=
  bgp:
    asn: 4242420458
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-131
  peer_v4: 172.21.109.36
  peer_v6: fe80::1131
  port: 21131
  remote: tokyo.japan.dn42.yuzu.im:21080
  wg_pubkey: 7ZLEhruv0R7V9DUEv+BHLr5fszpp/B55aKFtVoIACno=
  bgp:
    asn: 4242421131
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sunnet
  peer_v4: 172.21.100.190
  peer_v6: fe80::3088:190
  port: 23088
  remote: tyo1-jp.dn42.6700.cc:21080
  wg_pubkey: b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0=
  bgp:
    asn: 4242423088
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-link2
  peer_v4: 172.21.109.17
  peer_v6: fe80::864:1
  port: 20864
  remote: tyo.dn42.christine.pp.ua:21080
  wg_pubkey: 6x6cydEpu7OpSy6kaMyEVSA869gmvy4OcLx2IpMZRxs=
  bgp:
    asn: 4242420864
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.tyo1.routedbits.com:51080
  wg_pubkey: Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-boletus
  port: 20398
  remote: nrt.dn42.boletus.icu:21080
  wg_pubkey: QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho=
  peer_v4: null
  peer_v6: fe80::398
  bgp:
    asn: 4242420398
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-c4tg
  port: 21411
  remote: kaeru.catgirls.systems:21080
  wg_pubkey: o5li7EO9pSR0DaUoykcsnOlw8nhOQWJNFVCyJ7Z66CI=
  peer_v4: null
  peer_v6: fe80::1411:6
  bgp:
    asn: 4242421411
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-cdubs
  port: 20566
  remote: dn19.tyo.surgebytes.com:31080
  wg_pubkey: enL0F9LLRy7INDskyBCxgLknK5TBr/bwkD0LEGioNxw=
  peer_v4: null
  peer_v6: fe80::566:19
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sdubs
  port: 20202
  remote: dn03.to.jp.sdubs.vip:21080
  wg_pubkey: jkhbCLVZQ8BRoPOfdC+e3+jDYE+/OqPlZzTh9p9i8FA=
  peer_v4: null
  peer_v6: fe80::202:3
  bgp:
    asn: 4242420202
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-lantian
  port: 22547
  remote: oracle-vm1.lantian.pub:21080
  wg_pubkey: JJUfHeE1ZgyXzo5aoE0tQfk6wZvnVU/d0V3/uSj61ns=
  peer_v4: 172.22.76.123
  peer_v6: fe80::2547
  bgp:
    asn: 4242422547
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-duststars
  port: 21771
  remote: tyo1.exploro.one:32583
  wg_pubkey: bYG9mG2WvvzO8P9GoSJTP/DmwjeWPlR9j2uH3avnJAU=
  peer_v4: null
  peer_v6: fe80::1771
  bgp:
    asn: 4242421771
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true


- name: dn42-cowgl
  port: 23999
  remote: tyo.node.cowgl.xyz:31080
  wg_pubkey: mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE=
  peer_v4: 172.22.144.65
  peer_v6: "fd36:62be:ef51:1::1"
  bgp:
    asn: 4242423999
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-luoyu
  port: 21999
  remote: 156.231.112.158:21080
  wg_pubkey: vzCKl611U0MVeaIcNyb8gJgWk1p6HY6oHr1oE846Py8=
  peer_v4: 172.23.11.42
  peer_v6: fe80::1999
  bgp:
    asn: 4242421999
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-bitrate
  port: 23997
  remote: jp1.dn42.bitrate.studio:21080
  wg_pubkey: wsjN0FgfZBFzSZQ66biOkYRtyQWWMFvX3ICOwj70D0U=
  peer_v4: 172.21.95.34
  peer_v6: fe80::3997
  bgp:
    asn: 4242423997
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-mxmilu
  port: 21166
  remote: jp.dn42.milu.moe:21080
  wg_pubkey: KEvc8ZVx68bazeY2XO4LDIb3PAxFtiQSTY5xNesTFDc=
  peer_v4: 172.22.110.33
  peer_v6: fe80::1166
  bgp:
    asn: 4242421166
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-xeiu
  port: 21336
  remote: jp1.dn42.xeiu.top:21080
  wg_pubkey: eacDn4IjHBMavV9IeilwPmrVDoVyKBkNhgK6qUBskiM=
  peer_v4: 172.20.159.1
  peer_v6: fe80::1336
  bgp:
    asn: 4242421336
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-iyoroy
  port: 22024
  remote: ipv4.tyo-jp.ecs.iyoroy-infra.top:21080
  wg_pubkey: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
  peer_v4: 172.20.234.227
  peer_v6: fe80::2024
  bgp:
    asn: 4242422024
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-fmepnet
  port: 23703
  remote: jp-tyo0.fmepnet.org:41080
  wg_pubkey: Vk/e45UgKJzTdFLBdU/09CRmrMDtWft1uORyO4Otk0I=
  peer_v4: 172.20.159.234
  peer_v6: fe80::3703:234
  bgp:
    asn: 4242423703
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-maiyun
  port: 20893
  remote: jp02.dn42.maiyun.me:24213
  wg_pubkey: J5aq5AYRv/GHfr90mVEOPRCQeLInGS3mnSpckuyWt04=
  peer_v4: null
  peer_v6: fe80::893
  bgp:
    asn: 4242420893
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-factor2431
  port: 21534
  remote: jp-tyo.factor2431.com:21080
  wg_pubkey: XYyk/uk3LTHk7vOqtDsDh/AcPtdT3qQptqhggzZCRio=
  peer_v4: null
  peer_v6: fe80::1534
  bgp:
    asn: 4242421534
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-moohr
  port: 22279
  remote: jp-nrt1.bb.mhr.hk:21080
  wg_pubkey: Bt0gmHMrBBCgV8/k7n8ykA31YStGc55xmyLgMyB04E0=
  peer_v4: 172.23.77.200
  peer_v6: fe80::2279
  bgp:
    asn: 4242422279
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-stevie
  port: 20337
  remote: tyo01.dn42.wwrr.ru:21080
  wg_pubkey: xZBEeAO1btrRvU7cpXTBqaw8CZsmxrfB0005OgljtmU=
  peer_v4: null
  peer_v6: fe80::337
  bgp:
    asn: 4242420337
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-moraxyc
  port: 23011
  remote: jp2.dn42.moraxyc.com:21080
  wg_pubkey: 5Sq33dQ6Hox8lpda0wve08scNBc7BSDjaP4EPYKjdVk=
  peer_v4: null
  peer_v6: fe80::3011
  bgp:
    asn: 4242423011
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-iris
  port: 21023
  remote: tyo-01.node.svc.moe:21080
  wg_pubkey: pv0bwaUm/ppI7Yaoi7w0qrXX5EW7Qo2njTSNG19AHgM=
  peer_v4: null
  peer_v6: fe80::1023:2
  bgp:
    asn: 4242421023
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-fxnet
  port: 20014
  remote: jp.dn42.fxnet.top:21080
  wg_pubkey: RwS9qiSqkptO9QTje9stsxRD1CA/CR5HaDdNdPBydyU=
  peer_v4: null
  peer_v6: fe80::0014:4
  bgp:
    asn: 4242420014
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-yuyuko
  port: 21117
  remote: jp01.dn42.yuyuko.com:21080
  wg_pubkey: vZXB25Od9elWU4RKWp42MWNJrNtxJFgdmBkyYH/8Sj8=
  peer_v4: null
  peer_v6: fe80::1117
  bgp:
    asn: 4242421117
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-hexpnetwor
  port: 20298
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33353330363564303532346138363435346237333837646238626362393930313438353933303661
    3230633435653539353637313434636537356362353365300a626130626136396135616233633362
    30613062373935326434366637376265333662353364353234383034333633343263373836316531
    3633313761333032350a323339363731393438616132373636333461333664626138306461376566
    33656432323263386638303937376466663963306338303866383466623766313036
  wg_pubkey: THuvCjQInL2OItAM+gRoeobEUJ/Dbo+pau1Yg9FGqWY=
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34656533363965633237623933383331396535376532616239396332393530336536303466616261
    3730383633373230383564373934623638376261636634620a653662373436353939643736666166
    63643165356638663666353139386438353738333733373630363939343863323338383465613330
    3364383930326439650a666561396365656539623433323264616566346531663431393366303139
    33666634306238363563396164303262636330346233616633366238396265613935366662376266
    3730623334333463346336633564376563303666626665366265
  peer_v4: null
  peer_v6: fe80::298
  bgp:
    asn: 4242420298
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-bingxin
  port: 23374
  remote: jp01.dn42.baka.pub:21080
  wg_pubkey: N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0=
  peer_v4: null
  peer_v6: fe80::2999:226
  bgp:
    asn: 4242423374
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-timxzhao
  port: 23388
  remote: tyo-01.xinzhao.ca:21080
  wg_pubkey: +17JAejB0E6d2RGAb6ItBpmtd3eaNV2o2PQ441iIWwk=
  peer_v4: null
  peer_v6: fe80::3388
  bgp:
    asn: 4242423388
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
