wg_peers:
- name: dn42-tech9
  port: 51588
  remote: "jp-tyo01.dn42.tech9.io:52952"
  wg_pubkey: "unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM="
  peer_v4: "172.20.16.145/32"
  peer_v6: "fe80::1588/64"
  local_v6: "fe80::100"
  bgp:
    asn: 4242421588
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false
    export_mode: prepend

- name: dn42-yura
  port: 22464
  remote: "nrt.dneo.moeternet.com:21080"
  wg_pubkey: "tDNRiZDVxwzdYdoi+5ydgLwpVu252aP7y+NKxfAzyVY="
  peer_v4: null
  peer_v6: "fe80::2464/64"
  bgp:
    asn: 4242422464
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-jerry
  port: 53618
  remote: jpn.neo.jerryxiao.cc:50101
  wg_pubkey: "7c3/iRHLHL/DGPacgZf+JSnNBtKT4fUKaQw2xPUpAGE="
  peer_v4: null
  peer_v6: "fe80::3618/64"
  bgp:
    asn: 4242423618
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-kskb1817
  port: 21817
  remote: "4.jp.kskb.eu.org:21080"
  wg_pubkey: "jxCsSXtUSVjaP+eMWOyRsHg3JShQfBFEtyssMKWQaS8="
  peer_v4: null
  peer_v6: "fe80::42:1817:1"
  bgp:
    asn: 4242421817
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-yuuta
  port: 52980
  remote: "tyo1.jp.dn42.yuuta.moe:21080"
  wg_pubkey: "4O3EO93PdKwo37UuKVmtXmTGh/tSJbQBcZJc+Yh3XRw="
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63643033623733346561643137326366613736366233666638303331333664393132613430363730
    3766656235363735636362643265616437336437656332340a383337656231316631323434363637
    33343234333034653561663763613939373062393161393461343837333838326431653631303437
    6235373838383630380a656638313338373563386464306265306332323061323131376463363937
    64346162356161363636326432653562383735376261613661363032386163316332366530656332
    3265643836323665333639306561346165666262353032343565
  peer_v4: "172.23.105.2"
  peer_v6: "fe80::2980"
  bgp:
    asn: 4242422980
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-iedon
  port: 22189
  remote: jp-tyo.dn42.kuu.moe:54764
  wg_pubkey: u2ImAJn9ewce9YHN6HaqrR3Sr4Xsy5UaaJOLJ7gkSzs=
  peer_v4: null
  peer_v6: fe80::2189:ee
  bgp:
    asn: 4242422189
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-yurui
  port: 52330
  remote: "tp01.tw.node.argonauts.xyz:51080"
  wg_pubkey: "LNpOdAZMc2RszmMB/JrvGoqLt8aE+p9JyYODKphzyyw="
  peer_v4: "172.23.32.5"
  peer_v6: "fe80::2330:5"
  bgp:
    asn: 4242422330
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-kskb
  peer_v4: 10.127.111.9
  peer_v6: fe80::aa:1111:9
  port: 21111
  remote: null
  wg_pubkey: 2CxGhL9UwlCB3ybwD1OF2Or18vCPgChS0rdh3Nc8S0c=
  bgp:
    asn: 4201271111
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030
  port: 22717
  remote: jp.vm.whojk.com:23014
  wg_pubkey: ifN+KmnL5XLHG8nDi2nN9l26snGUP/1157p8mOSPE1c=
  bgp:
    asn: 4242422717
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: jp1.dn42.atolm.net:21080
  wg_pubkey: UNSqegT4PRWe6507kvlMsqj5YKxdcvQe2zedDL0k8Ww=
  bgp:
    asn: 4242420585
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: jp1.nodes.huajinet.org:21080
  wg_pubkey: lLcWnM8vTogYe4H96zSeKmtz8MBL+g0ajnMcFDsYIk8=
  bgp:
    asn: 4242420458
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-131
  peer_v4: 172.21.109.36
  peer_v6: fe80::1131
  port: 21131
  remote: tokyo.japan.dn42.yuzu.im:21080
  wg_pubkey: 7ZLEhruv0R7V9DUEv+BHLr5fszpp/B55aKFtVoIACno=
  bgp:
    asn: 4242421131
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sunnet
  peer_v4: 172.21.100.190
  peer_v6: fe80::3088:190
  port: 23088
  remote: tyo1-jp.dn42.6700.cc:21080
  wg_pubkey: b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0=
  bgp:
    asn: 4242423088
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-link2
  peer_v4: 172.21.109.17
  peer_v6: fe80::864:1
  port: 20864
  remote: tyo.dn42.christine.pp.ua:21080
  wg_pubkey: 6x6cydEpu7OpSy6kaMyEVSA869gmvy4OcLx2IpMZRxs=
  bgp:
    asn: 4242420864
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-tavimori
  port: 20950
  remote: tyo.dn42.lcblue.net:21080
  wg_pubkey: sFw/u+6a/E3yv3UzTzZdO5oXQAqPtZ/HqaOMVaOMNmI=
  peer_v4: 172.20.181.253
  peer_v6: fe80::b05c:3fbb:ee9a:fc4d
  wg_mtu: 1320
  bgp:
    asn: 4242420950
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-routedbits
  port: 20207
  remote: router.tyo1.routedbits.com:51080
  wg_pubkey: Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs=
  peer_v4: null
  peer_v6: fe80::207
  bgp:
    asn: 4242420207
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-akihi
  port: 20398
  remote: nrt.dn42.boletus.me:21080
  wg_pubkey: /EDDHZQrfLv9XeKMYOp8XdEFEB9ml3BE/YwV5UhN5W0=
  peer_v4: null
  peer_v6: fe80::426f
  bgp:
    asn: 4242420398
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-c4tg
  port: 21411
  remote: kaeru.catgirls.systems:21080
  wg_pubkey: o5li7EO9pSR0DaUoykcsnOlw8nhOQWJNFVCyJ7Z66CI=
  peer_v4: null
  peer_v6: fe80::1411:6
  bgp:
    asn: 4242421411
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: cl-roam
  local_v4: 172.22.108.102/31
  local_v6: null
  port: 19997
  multi:
  - wg_pubkey: "krMnDawVDAurrJqWkePFp1vE2zwK2vQy6ie6tGLcnX0="
    wg_allowedips: "172.22.108.103/32"
  peer_v6: null

- name: dn42-cdubs
  port: 20566
  remote: dn19.tyo.surgebytes.com:31080
  wg_pubkey: enL0F9LLRy7INDskyBCxgLknK5TBr/bwkD0LEGioNxw=
  peer_v4: null
  peer_v6: fe80::566:19
  bgp:
    asn: 4242420566
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-sdubs
  port: 20202
  remote: dn03.to.jp.sdubs.vip:21080
  wg_pubkey: jkhbCLVZQ8BRoPOfdC+e3+jDYE+/OqPlZzTh9p9i8FA=
  peer_v4: null
  peer_v6: fe80::202:3
  bgp:
    asn: 4242420202
    extended_next_hop: true
    ipv4: true
    ipv6: true
    mp_bgp: true

- name: dn42-joenet
  port: 20157
  remote: tyo01.ke8jwh.com:31080
  wg_pubkey: 8/TRCsEGBnmYwePBlnyajoPYSVoPJ46aNmH40mGAXFk=
  peer_v4: null
  peer_v6: fe80::157:236
  bgp:
    asn: 4242420157
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-stepnem
  port: 21282
  remote: jp-tyo1.dn42.smrk.net:21080
  wg_pubkey: sgHPjsqtu7vh5U5T1DaXtinC9RHrWQpVzxm4qEnzpyw=
  peer_v4: null
  peer_v6: fe80::1282
  bgp:
    asn: 4242421282
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-lantian
  port: 22547
  remote: oracle-vm1.lantian.pub:21080
  wg_pubkey: JJUfHeE1ZgyXzo5aoE0tQfk6wZvnVU/d0V3/uSj61ns=
  peer_v4: 172.22.76.123
  peer_v6: fe80::2547
  bgp:
    asn: 4242422547
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-duststars
  port: 21771
  remote: tokyo1.exploro.one:32583
  wg_pubkey: P8a4I7LXo976Fyh4ChJ/T6+lxna4gHjJk3SOHxtPSXw=
  peer_v4: null
  peer_v6: fe80::afaf:bfbf:cdcf:3a
  bgp:
    asn: 4242421771
    ipv4: false
    ipv6: true
    mp_bgp: false
    extended_next_hop: false

- name: dn42-cowgl
  port: 23999
  remote: tyo.node.cowgl.xyz:31080
  wg_pubkey: mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE=
  peer_v4: 172.22.144.65
  peer_v6: "fd36:62be:ef51:1::1"
  bgp:
    asn: 4242423999
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: false

- name: dn42-luoyu
  port: 21999
  remote: 156.231.112.158:21080
  wg_pubkey: vzCKl611U0MVeaIcNyb8gJgWk1p6HY6oHr1oE846Py8=
  peer_v4: 172.23.11.42
  peer_v6: fe80::1999
  bgp:
    asn: 4242421999
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-liekong
  port: 20070
  remote: jp.dn42.lie-kong.top:21080
  wg_pubkey: PA5hDpcgaKsYKUyI3lLMcYojivg5LRfBuyOSsKTq1mY=
  peer_v4: 172.20.53.33
  peer_v6: fe80::0070:1
  bgp:
    asn: 4242420070
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-bitrate
  port: 23997
  remote: jp1.dn42.bitrate.studio:21080
  wg_pubkey: wsjN0FgfZBFzSZQ66biOkYRtyQWWMFvX3ICOwj70D0U=
  peer_v4: 172.21.95.34
  peer_v6: fe80::3997
  bgp:
    asn: 4242423997
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-mxmilu
  port: 21166
  remote: jp.dn42.milu.moe:21080
  wg_pubkey: KEvc8ZVx68bazeY2XO4LDIb3PAxFtiQSTY5xNesTFDc=
  peer_v4: 172.22.110.33
  peer_v6: fe80::1166
  bgp:
    asn: 4242421166
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-xeiu
  port: 21336
  remote: jp1.dn42.xeiu.top:21080
  wg_pubkey: eacDn4IjHBMavV9IeilwPmrVDoVyKBkNhgK6qUBskiM=
  peer_v4: 172.20.159.1
  peer_v6: fe80::1336
  bgp:
    asn: 4242421336
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-iyoroy
  port: 22024
  remote: ipv4.tyo-jp.ecs.iyoroy-infra.top:21080
  wg_pubkey: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
  peer_v4: 172.20.234.227
  peer_v6: fe80::2024
  bgp:
    asn: 4242422024
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true

- name: dn42-fmepnet
  port: 23703
  remote: jp-tyo0.fmepnet.org:41080
  wg_pubkey: Vk/e45UgKJzTdFLBdU/09CRmrMDtWft1uORyO4Otk0I=
  peer_v4: 172.20.159.234
  peer_v6: fe80::3703:234
  bgp:
    asn: 4242423703
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: false

- name: dn42-maiyun
  port: 20893
  remote: jp02.dn42.maiyun.me:24213
  wg_pubkey: J5aq5AYRv/GHfr90mVEOPRCQeLInGS3mnSpckuyWt04=
  peer_v4: null
  peer_v6: fe80::893
  bgp:
    asn: 4242420893
    ipv4: true
    ipv6: true
    mp_bgp: true
    extended_next_hop: true
