wg_peers:
- name: dn42-tech9
  port: 51588
  remote: "jp-tyo01.dn42.tech9.io:52952"
  wg_pubkey: "unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM="
  peer_v4: "172.20.16.145/32"
  peer_v6: "fe80::1588/64"
  local_v6: "fe80::100"

- name: dn42-koala
  port: 51488
  remote: "tanuki.koala.gq:21080"
  wg_pubkey: "IL1Wkw5cLpGUUvFlYwAG4rAsw9lbd1QpTcBPsk/w/SM="
  peer_v4: null
  peer_v6: "fe80::3621"

- name: dn42-nicholascw
  port: 51288
  remote: "jpn1.sc00.org:21080"
  wg_pubkey: "gOcvbENQnONJ0SDgTPGVzukSHGALi1N7gRWuWuhk7hU="
  peer_v4: "172.20.233.130"
  peer_v6: "fe80::1288/64"

- name: dn42-yura
  port: 22464
  remote: "nrt.dneo.moeternet.com:21080"
  wg_pubkey: "tDNRiZDVxwzdYdoi+5ydgLwpVu252aP7y+NKxfAzyVY="
  peer_v4: null
  peer_v6: "fe80::2464/64"

- name: dn42-jerry
  port: 53618
  remote: jpn.neo.jerryxiao.cc:50101
  wg_pubkey: "7c3/iRHLHL/DGPacgZf+JSnNBtKT4fUKaQw2xPUpAGE="
  peer_v4: null
  peer_v6: "fe80::3618/64"

- name: dn42-sheepbrew
  remove: true

- name: dn42-kskb1817
  port: 21817
  remote: "4.jp.kskb.eu.org:21080"
  wg_pubkey: "jxCsSXtUSVjaP+eMWOyRsHg3JShQfBFEtyssMKWQaS8="
  peer_v4: null
  peer_v6: "fe80::42:1817:1"

- name: dn42-yuuta
  port: 52980
  remote: "tyo1.jp.dn42.yuuta.moe:21080"
  wg_pubkey: "4O3EO93PdKwo37UuKVmtXmTGh/tSJbQBcZJc+Yh3XRw="
  wg_presharedkey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    63643033623733346561643137326366613736366233666638303331333664393132613430363730
    3766656235363735636362643265616437336437656332340a383337656231316631323434363637
    33343234333034653561663763613939373062393161393461343837333838326431653631303437
    6235373838383630380a656638313338373563386464306265306332323061323131376463363937
    64346162356161363636326432653562383735376261613661363032386163316332366530656332
    3265643836323665333639306561346165666262353032343565
  peer_v4: "172.23.105.2"
  peer_v6: "fe80::2980"

- name: dn42-iedon
  port: 22189
  remote: jp-tyo.dn42.kuu.moe:54764
  wg_pubkey: u2ImAJn9ewce9YHN6HaqrR3Sr4Xsy5UaaJOLJ7gkSzs=
  peer_v4: null
  peer_v6: fe80::2189:ee

- name: dn42-yurui
  port: 52330
  remote: "tp01.tw.node.argonauts.xyz:51080"
  wg_pubkey: "LNpOdAZMc2RszmMB/JrvGoqLt8aE+p9JyYODKphzyyw="
  peer_v4: "172.23.32.5"
  peer_v6: "fe80::2330:5"

- name: dn42-hinata
  port: 53724
  remote: "tyo01.jp.42.katohinata.eu.org:21080"
  wg_pubkey: "zhtttxYDZtt/iIdm5HqG5G+g7iJHciJwLbLB/6Rjy1s="
  peer_v4: "172.23.215.226"
  peer_v6: "fe80::3724"

- name: dn42-myon
  port: 20639
  remote: null
  wg_pubkey: "YfMA5dAA3CRMWXb/ONQk5sjnrpz+Bsrj6Azj1+nx4nc="
  peer_v4: "172.22.177.87"
  peer_v6: "fe80::639"

- name: dn42-melty
  port: 23632
  remote: "cranberry.link.melty.land:21080"
  wg_pubkey: "uXeP5y2MP+XBcI7EU8LxqGS1r/Fu3vGIl3Q+r24J0UI="
  peer_v4: "172.23.36.34"
  peer_v6: "fe80::3632"

- name: dn42-kskb
  peer_v4: 10.127.111.9
  peer_v6: fe80::aa:1111:9
  port: 21111
  remote: null
  wg_pubkey: 2CxGhL9UwlCB3ybwD1OF2Or18vCPgChS0rdh3Nc8S0c=

- name: dn42-186526
  peer_v4: 172.23.2.95
  peer_v6: fe80::ade1
  port: 23764
  remote: jp-tokyo-02.edge.186526.xyz:21080
  wg_pubkey: p1U1flETVuiZjghZhannbcrQxdp3fiLodVqs8Xy3ZFo=

- name: dn42-hujk
  peer_v4: null
  peer_v6: fe80::104:50:2030
  port: 22717
  remote: jp.vm.whojk.com:23014
  wg_pubkey: ifN+KmnL5XLHG8nDi2nN9l26snGUP/1157p8mOSPE1c=

- name: dn42-atolm
  peer_v4: null
  peer_v6: fe80::585
  port: 20585
  remote: jp1.dn42.atolm.net:21080
  wg_pubkey: UNSqegT4PRWe6507kvlMsqj5YKxdcvQe2zedDL0k8Ww=

- name: dn42-huajitech
  peer_v4: null
  peer_v6: fe80::458
  port: 20458
  remote: jp1.nodes.huajinet.org:21080
  wg_pubkey: lLcWnM8vTogYe4H96zSeKmtz8MBL+g0ajnMcFDsYIk8=

- name: dn42-131
  peer_v4: 172.21.109.36
  peer_v6: fe80::1131
  port: 21131
  remote: tokyo.japan.dn42.yuzu.im:21080
  wg_pubkey: 7ZLEhruv0R7V9DUEv+BHLr5fszpp/B55aKFtVoIACno=

- name: dn42-chimon
  peer_v4: 172.21.65.164
  peer_v6: fe80::3868
  port: 23868
  remote: kix1.dn42.cooo.cool:21080
  wg_pubkey: a8pgJK98XGV9gFWvJv4CirkRcbeHzbevQJnci45hhTc=

- name: dn42-bbpgqm
  peer_v4: 172.20.56.4
  peer_v6: fe80::549:3921:0:1
  port: 20549
  remote: tyo.dn42.bb-pgqm.com:21080
  wg_pubkey: 9wF7vXyJ+uBUb3At/SODOkaBSEQSdvpdtCwRL9kiuFc=

- name: dn42-sunnet
  peer_v4: 172.21.100.190
  peer_v6: fe80::3088:190
  port: 23088
  remote: tyo1-jp.dn42.6700.cc:21080
  wg_pubkey: b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0=

- name: dn42-link2
  peer_v4: 172.21.109.17
  peer_v6: fe80::864:1
  port: 20864
  remote: tyo.dn42.christine.pp.ua:21080
  wg_pubkey: 6x6cydEpu7OpSy6kaMyEVSA869gmvy4OcLx2IpMZRxs=

- name: dn42-pigeonhole
  peer_v4: 172.22.145.19
  peer_v6: fe80::2458
  port: 22458
  remote: jp-tyo-a.nodes.pigeonhole.eu.org:21080
  wg_pubkey: OEjDZMJF1USPznWEf2UbbdHexNAlP1/EKkKTN95Nx0Q=

- name: dn42-potat0
  remove: true

- name: dn42-tavimori
  port: 20950
  remote: tyo.dn42.lcblue.net:21080
  wg_pubkey: sFw/u+6a/E3yv3UzTzZdO5oXQAqPtZ/HqaOMVaOMNmI=
  peer_v4: 172.20.181.253
  peer_v6: fe80::b05c:3fbb:ee9a:fc4d
  wg_mtu: 1320

- name: dn42-lilynet
  peer_v4: 172.23.180.2
  peer_v6: fe80::1d90
  port: 21877
  remote: suzuran.lilynet.work:21080
  wg_pubkey: E/+f5HM2EEw7CV574nYj+51bRNJDOZ6C5BKSQBpMGgw=

- name: dn42-wenlong
  port: 22366
  remote: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36636462383265313930656634616333306461333835646664633832313164333661646661666638
    3131643938396663333532343032613037326362653134310a333439666264323564393337316566
    33656639393738656161373564626439356565383439303562396636633630323136326338363538
    6465323163306163630a333436396133353639316362363532633530356339383066316135383665
    30356334356265323936633962653966646137336332383732383065363339616662
  wg_pubkey: kMrT8TeTYBnOXgpUR/Z8Vh38BZrLGCL3s2G7FaIEyyM=
  peer_v4: 172.22.109.161
  peer_v6: fe80::1423:1

- name: dn42-sernet
  port: 23947
  remote: kr-sel1.dn42.sherpherd.top:21080
  wg_pubkey: z3kzVGVqgqxpWGF5iKZ90+aL01hU7gZZ5ieVHJsbdS8=
  peer_v4: null
  peer_v6: fe80::3947:5

- name: dn42-routedbits
  port: 20207
  remote: router.tyo1.routedbits.com:51080
  wg_pubkey: Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs=
  peer_v4: null
  peer_v6: fe80::207

- name: dn42-akihi
  port: 20398
  remote: hnd.dn42.akihi.me:21080
  wg_pubkey: /EDDHZQrfLv9XeKMYOp8XdEFEB9ml3BE/YwV5UhN5W0=
  peer_v4: null
  peer_v6: fe80::426f

- name: dn42-c4tg
  port: 21411
  remote: kaeru.catgirls.systems:21080
  wg_pubkey: o5li7EO9pSR0DaUoykcsnOlw8nhOQWJNFVCyJ7Z66CI=
  peer_v4: null
  peer_v6: fe80::1411:6

- name: cl-roam
  local_v4: 172.22.108.102/31
  local_v6: null
  port: 19997
  multi:
  - wg_pubkey: "krMnDawVDAurrJqWkePFp1vE2zwK2vQy6ie6tGLcnX0="
    wg_allowedips: "172.22.108.103/32"
  peer_v6: null

- name: dn42-cmcc
  remove: true

- name: dn42-cdubs
  remove: true
