# This is already read in once as part of group_vars/all, but the values may have been changed
# by scripts/enumerate-igp-tunnels.py: pre_tasks still run after enumerating facts the first time
- name: Read IGP tunnel settings
  include_vars:
    file: "global-config/igp-tunnels.yml"

- name: Read Wireguard settings for peers
  include_vars:
    file: "{{ playbook_dir }}/roles/config-wireguard/config/{{ inventory_hostname }}.yml"
  ignore_errors: true

- name: Read OpenVPN settings for peers
  include_vars:
    file: "{{ playbook_dir }}/roles/config-openvpn/config/{{ inventory_hostname }}.yml"
  ignore_errors: true

- name: Read GRE settings for peers
  include_vars:
    file: "{{ playbook_dir }}/roles/config-gre-plain/config/{{ inventory_hostname }}.yml"
  ignore_errors: true

- name: "Read iptables rules template"
  set_fact:
    iptables_rules: "{{ lookup('template', 'templates/rules.j2') }}"
  vars:
    my_cidrs: "{{ ownnets4 | join(',') }}"
    aftype: 4

- name: "Read iptables rules template"
  set_fact:
    ip6tables_rules: "{{ lookup('template', 'templates/rules.j2') }}"
  vars:
    my_cidrs: "{{ ownnets6 | join(',') }}"
    aftype: 6

- name: "Create iptables rules folder"
  file:
    path: "{{ iptables_dir }}"
    state: directory

- name: "Template iptables apply script"
  template:
    src: apply.j2
    dest: "{{ iptables_dir }}/apply"
    mode: '755'
  notify:
  - "Reload iptables rules"

- name: "Write iptables rules for IPv4"
  blockinfile:
    dest: "{{ iptables_rules_path }}"
    content: '{{ iptables_rules }}'
    insertafter: "\\*filter"
    state: present
    #backup: yes
    validate: "iptables-restore --test %s"
    marker: "# {mark} ansible-dn42 managed block"
  notify:
  - "Reload iptables rules"

- name: "Write iptables rules for IPv6"
  blockinfile:
    dest: "{{ ip6tables_rules_path }}"
    content: '{{ ip6tables_rules }}'
    state: present
    insertafter: "^\\*filter$"
    #backup: yes
    validate: "ip6tables-restore --test %s"
    marker: "# {mark} ansible-dn42 managed block"
  notify:
  - "Reload iptables rules"
